package seed

var SeedCategories = []SeedJobCategory{
	{ExternalID: "it", Name: "IT | 互联网", ParentExternalID: "", OrderNum: 10, IsActive: true},
	{ExternalID: "finance", Name: "金融 | 银行", ParentExternalID: "", OrderNum: 20, IsActive: true},
	{ExternalID: "education", Name: "教育 | 培训", ParentExternalID: "", OrderNum: 30, IsActive: true},
	{ExternalID: "healthcare", Name: "医疗 | 健康", ParentExternalID: "", OrderNum: 40, IsActive: true},
	{ExternalID: "realestate", Name: "建筑 | 房地产", ParentExternalID: "", OrderNum: 50, IsActive: true},
	{ExternalID: "manufacturing", Name: "制造 | 生产", ParentExternalID: "", OrderNum: 60, IsActive: true},
	{ExternalID: "logistics", Name: "交通 | 物流", ParentExternalID: "", OrderNum: 70, IsActive: true},
	{ExternalID: "services", Name: "服务 | 消费", ParentExternalID: "", OrderNum: 80, IsActive: true},
	{ExternalID: "media", Name: "文化 | 传媒", ParentExternalID: "", OrderNum: 90, IsActive: true},
	{ExternalID: "trade", Name: "贸易 | 进出口", ParentExternalID: "", OrderNum: 100, IsActive: true},
	{ExternalID: "energy", Name: "能源 | 环保", ParentExternalID: "", OrderNum: 110, IsActive: true},
	{ExternalID: "agriculture", Name: "农林 | 牧渔", ParentExternalID: "", OrderNum: 120, IsActive: true},
	{ExternalID: "public", Name: "公共 | 非盈利", ParentExternalID: "", OrderNum: 130, IsActive: true},
	{ExternalID: "others", Name: "其他 | 岗位", ParentExternalID: "", OrderNum: 140, IsActive: true},

	{ExternalID: "it_backend", Name: "后端开发/程序员", ParentExternalID: "it", OrderNum: 10, IsActive: true},
	{ExternalID: "it_frontend", Name: "前端开发", ParentExternalID: "it", OrderNum: 20, IsActive: true},
	{ExternalID: "it_mobile", Name: "移动开发", ParentExternalID: "it", OrderNum: 30, IsActive: true},
	{ExternalID: "it_testing", Name: "软件测试", ParentExternalID: "it", OrderNum: 40, IsActive: true},
	{ExternalID: "it_ops_sec_dba", Name: "运维 / 安全 / DBA", ParentExternalID: "it", OrderNum: 50, IsActive: true},
	{ExternalID: "it_ai_bigdata", Name: "新兴技术", ParentExternalID: "it", OrderNum: 60, IsActive: true},
	{ExternalID: "it_other_tech", Name: "其他技术岗", ParentExternalID: "it", OrderNum: 70, IsActive: true},
	{ExternalID: "it_senior", Name: "高端技术职位", ParentExternalID: "it", OrderNum: 80, IsActive: true},

	{ExternalID: "finance_counter_service", Name: "银行柜台/服务", ParentExternalID: "finance", OrderNum: 10, IsActive: true},
	{ExternalID: "finance_personal_wealth", Name: "个人金融与理财", ParentExternalID: "finance", OrderNum: 20, IsActive: true},
	{ExternalID: "finance_credit_approval", Name: "信贷/审批", ParentExternalID: "finance", OrderNum: 30, IsActive: true},
	{ExternalID: "finance_risk_compliance", Name: "风险管理/合规", ParentExternalID: "finance", OrderNum: 40, IsActive: true},
	{ExternalID: "finance_securities_invest", Name: "证券与投资", ParentExternalID: "finance", OrderNum: 50, IsActive: true},
	{ExternalID: "finance_insurance_actuary", Name: "保险/精算", ParentExternalID: "finance", OrderNum: 60, IsActive: true},
	{ExternalID: "finance_banking_support", Name: "银行业务支持", ParentExternalID: "finance", OrderNum: 70, IsActive: true},
	{ExternalID: "finance_trust_futures", Name: "信托/期货类", ParentExternalID: "finance", OrderNum: 80, IsActive: true},
	{ExternalID: "finance_bank_management", Name: "银行管理类岗位", ParentExternalID: "finance", OrderNum: 90, IsActive: true},
	{ExternalID: "finance_intern", Name: "银行新人/实习生", ParentExternalID: "finance", OrderNum: 100, IsActive: true},

	{ExternalID: "education_teacher", Name: "教师", ParentExternalID: "education", OrderNum: 10, IsActive: true},
	{ExternalID: "education_teaching_admin", Name: "教学管理", ParentExternalID: "education", OrderNum: 20, IsActive: true},
	{ExternalID: "education_student_services", Name: "学生服务", ParentExternalID: "education", OrderNum: 30, IsActive: true},
	{ExternalID: "education_training_lecturer", Name: "培训/讲师", ParentExternalID: "education", OrderNum: 40, IsActive: true},
	{ExternalID: "education_training_management", Name: "培训管理", ParentExternalID: "education", OrderNum: 50, IsActive: true},

	{ExternalID: "healthcare_doctor", Name: "医生", ParentExternalID: "healthcare", OrderNum: 10, IsActive: true},
	{ExternalID: "healthcare_nurse", Name: "护士", ParentExternalID: "healthcare", OrderNum: 20, IsActive: true},
	{ExternalID: "healthcare_medtech", Name: "医学技术岗", ParentExternalID: "healthcare", OrderNum: 30, IsActive: true},
	{ExternalID: "healthcare_pharma", Name: "药学岗", ParentExternalID: "healthcare", OrderNum: 40, IsActive: true},
	{ExternalID: "healthcare_devices", Name: "医疗器械岗", ParentExternalID: "healthcare", OrderNum: 50, IsActive: true},
	{ExternalID: "healthcare_other", Name: "其他医疗岗", ParentExternalID: "healthcare", OrderNum: 60, IsActive: true},
	{ExternalID: "healthcare_intern", Name: "医药实习", ParentExternalID: "healthcare", OrderNum: 70, IsActive: true},
	{ExternalID: "healthcare_management", Name: "医疗管理", ParentExternalID: "healthcare", OrderNum: 80, IsActive: true},

	{ExternalID: "realestate_design_planning", Name: "建筑设计/规划", ParentExternalID: "realestate", OrderNum: 10, IsActive: true},
	{ExternalID: "realestate_interior_landscape", Name: "室内/景观设计", ParentExternalID: "realestate", OrderNum: 20, IsActive: true},
	{ExternalID: "realestate_cost_budget", Name: "工程造价/预算", ParentExternalID: "realestate", OrderNum: 30, IsActive: true},
	{ExternalID: "realestate_construction_mgmt", Name: "工程施工/管理", ParentExternalID: "realestate", OrderNum: 40, IsActive: true},
	{ExternalID: "realestate_project_mgmt", Name: "项目管理", ParentExternalID: "realestate", OrderNum: 50, IsActive: true},
	{ExternalID: "realestate_sales_planning", Name: "房地产销售/策划", ParentExternalID: "realestate", OrderNum: 60, IsActive: true},
	{ExternalID: "realestate_property_mgmt", Name: "物业管理", ParentExternalID: "realestate", OrderNum: 70, IsActive: true},

	{ExternalID: "mfg_mechanical", Name: "机械制造", ParentExternalID: "manufacturing", OrderNum: 10, IsActive: true},
	{ExternalID: "mfg_electrical", Name: "电子/电气制造", ParentExternalID: "manufacturing", OrderNum: 20, IsActive: true},
	{ExternalID: "mfg_auto_transport", Name: "汽车/交通制造", ParentExternalID: "manufacturing", OrderNum: 30, IsActive: true},
	{ExternalID: "mfg_process_mold", Name: "工艺/模具工程", ParentExternalID: "manufacturing", OrderNum: 40, IsActive: true},
	{ExternalID: "mfg_prod_equip", Name: "生产/设备管理", ParentExternalID: "manufacturing", OrderNum: 50, IsActive: true},
	{ExternalID: "mfg_quality", Name: "质量管理", ParentExternalID: "manufacturing", OrderNum: 60, IsActive: true},
	{ExternalID: "mfg_rd_design", Name: "研发设计", ParentExternalID: "manufacturing", OrderNum: 70, IsActive: true},
	{ExternalID: "mfg_worker", Name: "生产技工", ParentExternalID: "manufacturing", OrderNum: 80, IsActive: true},

	{ExternalID: "logi_transport_service", Name: "运输服务", ParentExternalID: "logistics", OrderNum: 10, IsActive: true},
	{ExternalID: "logi_delivery", Name: "运输配送", ParentExternalID: "logistics", OrderNum: 20, IsActive: true},
	{ExternalID: "logi_warehouse", Name: "仓储管理", ParentExternalID: "logistics", OrderNum: 30, IsActive: true},
	{ExternalID: "logi_ops", Name: "物流运营", ParentExternalID: "logistics", OrderNum: 40, IsActive: true},
	{ExternalID: "logi_supply", Name: "供应链", ParentExternalID: "logistics", OrderNum: 50, IsActive: true},

	{ExternalID: "svc_food", Name: "餐饮服务", ParentExternalID: "services", OrderNum: 10, IsActive: true},
	{ExternalID: "svc_hotel_travel", Name: "酒店旅游", ParentExternalID: "services", OrderNum: 20, IsActive: true},
	{ExternalID: "svc_personal", Name: "个人服务", ParentExternalID: "services", OrderNum: 30, IsActive: true},
	{ExternalID: "svc_fitness", Name: "运动健身", ParentExternalID: "services", OrderNum: 40, IsActive: true},
	{ExternalID: "svc_beauty", Name: "美容保健", ParentExternalID: "services", OrderNum: 50, IsActive: true},
	{ExternalID: "svc_consult_translate", Name: "咨询翻译", ParentExternalID: "services", OrderNum: 60, IsActive: true},
	{ExternalID: "svc_repair", Name: "维修岗位", ParentExternalID: "services", OrderNum: 70, IsActive: true},
	{ExternalID: "svc_other", Name: "其他服务岗", ParentExternalID: "services", OrderNum: 80, IsActive: true},

	{ExternalID: "media_news_publishing", Name: "新闻/出版", ParentExternalID: "media", OrderNum: 10, IsActive: true},
	{ExternalID: "media_broadcast_tv", Name: "广播电视", ParentExternalID: "media", OrderNum: 20, IsActive: true},
	{ExternalID: "media_film_performance", Name: "影视演艺", ParentExternalID: "media", OrderNum: 30, IsActive: true},

	{ExternalID: "trade_foreign_trade", Name: "外贸业务", ParentExternalID: "trade", OrderNum: 10, IsActive: true},
	{ExternalID: "trade_trade_support", Name: "国际贸易支持", ParentExternalID: "trade", OrderNum: 20, IsActive: true},
	{ExternalID: "trade_crossborder_ecom", Name: "跨境电商", ParentExternalID: "trade", OrderNum: 30, IsActive: true},
	{ExternalID: "trade_translation_support", Name: "翻译支持", ParentExternalID: "trade", OrderNum: 40, IsActive: true},

	{ExternalID: "energy_traditional", Name: "传统能源", ParentExternalID: "energy", OrderNum: 10, IsActive: true},
	{ExternalID: "energy_environment", Name: "环境保护", ParentExternalID: "energy", OrderNum: 20, IsActive: true},

	{ExternalID: "agri_planting", Name: "农业种植", ParentExternalID: "agriculture", OrderNum: 10, IsActive: true},
	{ExternalID: "agri_forestry", Name: "林业", ParentExternalID: "agriculture", OrderNum: 20, IsActive: true},
	{ExternalID: "agri_livestock", Name: "畜牧业", ParentExternalID: "agriculture", OrderNum: 30, IsActive: true},
	{ExternalID: "agri_fishery", Name: "渔业水产", ParentExternalID: "agriculture", OrderNum: 40, IsActive: true},

	{ExternalID: "public_services", Name: "公共服务", ParentExternalID: "public", OrderNum: 10, IsActive: true},
	{ExternalID: "public_research", Name: "科研相关", ParentExternalID: "public", OrderNum: 20, IsActive: true},
	{ExternalID: "public_social", Name: "社会服务", ParentExternalID: "public", OrderNum: 30, IsActive: true},
}
