ARG TARGETPLATFORM
ARG TARGETARCH

FROM ghcr.io/browserless/chromium:latest

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    fonts-noto-cjk fonts-noto fonts-dejavu \
    && rm -rf /var/lib/apt/lists/*
