import React, { createContext, useContext, useState, ReactNode } from 'react';
import { Language } from '../types';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    'nav.templates': 'Templates',
    'nav.dashboard': 'My Resumes',
    'nav.pricing': 'Pricing',
    'nav.signin': 'Sign In',
    'nav.getStarted': 'Get Started',
    'nav.signout': 'Sign Out',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    'hero.title': 'Craft your perfect resume',
    'hero.subtitle': 'with AI precision',
    'hero.desc': 'Build professional, ATS-friendly resumes in minutes. Choose from our curated templates, use AI to polish your text, and land your dream job.',
    'hero.cta': 'Create Resume',
    'hero.cta_secondary': 'My Resumes',
    'home.popular': 'Popular Templates',
    'home.quickAccess': 'Quick Access',
    'common.edit': 'Edit',
    'common.share': 'Share',
    'common.preview': 'Preview',
    'common.duplicate': 'Duplicate',
    'common.delete': 'Delete',
    'common.rename': 'Rename',
    'common.save': 'Save',
    'common.download': 'Download',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.confirmAction': 'Confirm Action',
    'common.close': 'Close',
    'common.refresh': 'Refresh',
    'common.loading': 'Loading...',
    'common.copied': 'Copied',
    'common.copyFailed': 'Copy failed',
    'editor.content': 'Content',
    'editor.design': 'Design',
    'editor.personal': 'Personal Information',
    'editor.theme': 'Theme Settings',
    'editor.font': 'Font Family',
    'editor.spacing': 'Spacing & Density',
    'editor.color': 'Accent Color',
    'editor.ai_polish': 'AI Polish',
    'dashboard.title': 'My Resumes',
    'dashboard.createNew': 'Create New Resume',
    'common.toPresent': 'Present',
    'templates.title': 'Resume Templates',
    'templates.desc': 'Choose a professionally designed template to get started.',
    'templates.sidebar.navLabel': 'Job Category',
    'templates.hero.title': 'Find your perfect resume',
    'templates.hero.desc': 'Pick from professionally designed templates and variants to stand out.',
    'templates.filter.industry': 'Industry',
    'templates.filter.jobCategory': 'Job Category',
    'templates.filter.jobRole': 'Role',
    'templates.filter.level': 'Level',
    'templates.search': 'Search templates...',
    'templates.actions.search': 'Search',
    'templates.sort.latest': 'Latest',
    'templates.sort.hot': 'Hot',
    'templates.hotSearch': 'Popular:',
    'footer.rights': 'All rights reserved.',
    // Auth
    'auth.welcome': 'Welcome back',
    'auth.welcomeDesc': 'Enter your details to access your account.',
    'auth.orContinueWith': 'Or continue with',
    'auth.provider.github': 'GitHub',
    'auth.provider.wechat': 'WeChat',
    'auth.createAccount': 'Create an account',
    'auth.createDesc': 'Enter your email to get started.',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.verificationCode': 'Verification Code',
    'auth.sendCode': 'Send Code',
    'auth.sending': 'Sending...',
    'auth.resend': 'Send Code',
    'auth.login': 'Sign In',
    'auth.register': 'Sign Up',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.forgotPassword': 'Forgot password?',
    'auth.terms': 'By clicking continue, you agree to our Terms of Service and Privacy Policy.',
    'auth.error.invalidEmail': 'Please enter a valid email.',
    'auth.error.passwordMismatch': 'Passwords do not match.',
    'auth.error.invalidCode': 'Invalid verification code.',
    'auth.success.codeSent': 'Verification code sent to your email.',
    'auth.quote': 'Success is not final, failure is not fatal: it is the courage to continue that counts.',
    'auth.quoteAuthor': 'Winston Churchill',
    'auth.placeholder.email': 'you@example.com',
    'auth.placeholder.code': '123456',
    'auth.placeholder.password': '••••••••',
    'auth.placeholder.passwordMin': 'Min 6 characters',
    'auth.placeholder.reenterPassword': 'Re-enter password',
    'auth.error.fillAll': 'Please fill in all fields',
    'auth.error.invalidCredentials': 'Invalid email or password',
    'auth.error.general': 'An error occurred. Please try again.',
    'auth.error.sendCodeFailed': 'Failed to send code.',
    'auth.error.passwordTooShort': 'Password must be at least 6 characters.',
    'auth.error.registrationFailed': 'Registration failed.',
    'common.backHome': 'Back to Home',
    'footer.product': 'Product',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.language': 'Language',
    'lang.en': 'English',
    'lang.zh': 'Chinese',
    'lang.en_short': 'EN',
    'lang.zh_short': '中',
    'lang.switchToZh': 'Switch to Chinese',
    'lang.switchToEn': 'Switch to English',
    'lang.switchTitle': 'Switch Language',
    'a11y.openUserMenu': 'Open user menu',
    'a11y.signedInAs': 'Signed in as',
    'a11y.authBackgroundAlt': 'Auth Background',
    'a11y.avatarAlt': 'Avatar',
    'a11y.drag': 'Drag',
    'a11y.removePhoto': 'Remove photo',
    'home.actions.viewAll': 'View All',
    'home.actions.useTemplate': 'Use Template',
    'home.quick.it': 'IT / Tech',
    'home.quick.finance': 'Finance',
    'home.quick.creative': 'Creative',
    'home.quick.student': 'Student',
    'home.hero.alt': 'Resume planning',
    'features.title': 'Features',
    'features.subtitle': 'Everything you need to get hired',
    'features.ai.title': 'AI Writer & Polisher',
    'features.ai.desc': 'Stuck on words? Use our Gemini-powered AI to generate summaries and improve your bullet points instantly.',
    'features.ats.title': 'ATS Friendly Templates',
    'features.ats.desc': 'Our templates are designed to pass through Applicant Tracking Systems, ensuring your resume reaches human eyes.',
    'features.share.title': 'Share Online',
    'features.share.desc': 'Publish your resume with a unique link. Track views and share directly to LinkedIn or via QR code.',
    'features.preview.title': 'Real-time Preview',
    'features.preview.desc': 'See changes instantly as you type. Drag and drop sections to reorganize your story effortlessly.',
    'preview.pagesHint': 'Estimated pages: {count} pages',
    'preview.pageBreakTip.badge': 'Page Break Tip',
    'preview.pageBreakTip.modalTitle': 'Page Break Tip',
    'preview.pageBreakTip.modalDesc': 'This bar indicates a page break in the preview. If any content is covered by the bar, insert a line break (Enter) or adjust spacing/font size.',
    'preview.pageBreakTip.close': 'Close',
    'public.unavailable.title': 'Link unavailable',
    'public.unavailable.desc': 'This resume is no longer publicly accessible.',
    'public.expired.title': 'Link expired',
    'public.expired.desc': 'This share link has expired.',
    'public.password.title': 'Password required',
    'public.password.desc': 'Enter the password to view this resume.',
    'public.password.placeholder': 'Password',
    'public.password.submit': 'Unlock',
    'public.password.invalid': 'Incorrect password.',
    'rte.tooltip.bold': 'Bold',
    'rte.tooltip.italic': 'Italic',
    'rte.tooltip.bullets': 'Bulleted list',
    'rte.tooltip.undo': 'Undo',
    'rte.tooltip.redo': 'Redo',
    'templates.filters.label': 'Filters:',
    'templates.actions.useTemplate': 'Use Template',
    'templates.actions.clearAll': 'Clear all',
    'templates.actions.clearFilters': 'Clear Filters',
    'templates.meta.usageCount': 'Usage Count',
    'templates.empty': 'No templates found matching your criteria.',
    'templates.category.all': 'All',
    'templates.category.IT': 'IT',
    'templates.category.Finance': 'Finance',
    'templates.category.Creative': 'Creative',
    'templates.category.General': 'General',
    'templates.level.all': 'All',
    'templates.level.Intern': 'Intern',
    'templates.level.Junior': 'Junior',
    'templates.level.Senior': 'Senior',
    'templates.level.Executive': 'Executive',
    'editor.profile.label': 'Profile Photo',
    'editor.profile.upload': 'Upload Photo',
    'editor.profile.change': 'Change Photo',
    'editor.profile.tipMaxSize': 'Max size 2MB (JPG/PNG).',
    'editor.fields.fullName': 'Full Name',
    'editor.fields.jobTitle': 'Job Title',
    'editor.fields.email': 'Email',
    'editor.fields.phone': 'Phone',
    'editor.fields.website': 'Website / LinkedIn',
    'editor.fields.gender': 'Gender',
    'editor.fields.age': 'Age',
    'editor.fields.degree': 'Degree',
    'editor.fields.jobApplication': 'Desired Position',
    'editor.fields.city': 'Preferred City',
    'editor.fields.expectedSalary': 'Expected Salary',
    'editor.fields.joinTime': 'Join Time',
    'editor.customInfo.title': 'Custom Information',
    'editor.customInfo.add': 'Add Custom Item',
    'editor.customInfo.label': 'Label',
    'editor.customInfo.value': 'Value',
    'editor.placeholder.titleExample': 'Title (e.g., Senior Manager)',
    'editor.placeholder.subtitleExample': 'Subtitle (e.g., Company)',
    'editor.placeholder.dateRange': 'Date Range',
    'editor.placeholder.major': 'Major',
    'editor.placeholder.degree': 'Degree',
    'editor.placeholder.skills': 'List skills here...',
    'editor.placeholder.achievements': 'Describe your achievements...',
    'editor.labels.experience.title': 'Experience Title',
    'editor.labels.experience.role': 'Your Role',
    'editor.labels.projects.title': 'Project Name',
    'editor.labels.projects.role': 'Your Role',
    'editor.labels.education.school': 'School Name',
    'editor.labels.education.department': 'Department (optional)',
    'editor.labels.education.major': 'Major',
    'editor.labels.education.degree': 'Degree',
    'editor.labels.internships.company': 'Company Name',
    'editor.labels.common.startDate': 'Start Date',
    'editor.labels.common.endDate': 'End Date',
    'editor.labels.common.description': 'Description',
    'editor.ai.polishing': 'Polishing...',
    'editor.error.imageTooLarge': 'Image size too large. Please upload an image smaller than 2MB.',
    'editor.addItem': 'Add Item',
    'editor.font.group.englishSans': 'English - Sans Serif',
    'editor.font.group.englishSerif': 'English - Serif',
    'editor.font.group.englishMono': 'English - Mono',
    'editor.font.group.chineseSans': 'Chinese - Sans (黑体)',
    'editor.font.group.chineseSerif': 'Chinese - Serif (宋体/楷体)',
    'editor.font.note': 'Note: Chinese fonts rely on system availability or web fonts if supported.',
    'editor.spacing.option.compact': 'Compact (More Info)',
    'editor.spacing.option.normal': 'Normal (Balanced)',
    'editor.spacing.option.spacious': 'Spacious (Clean)',
    'editor.color.customTitle': 'Custom Color',
    'editor.fontSize': 'Font Size',
    'editor.back': 'Back',
    'editor.addSection': 'Add Custom Section',
    'editor.removeSection': 'Remove Section',
    'editor.rename': 'Rename Section',
    'editor.toggleVisibility': 'Toggle Visibility',
    'editor.template': 'Template',
    'editor.actions.changeTemplate': 'Change Template',
    'editor.language': 'Language',
    'editor.language.select': 'Select Language',
    'editor.save': 'Save',
    'editor.export.pdf': 'PDF',
    'editor.export.png': 'PNG',
    'download.selectFormat': 'Select your preferred format',
    'download.desc.pdf': 'High-quality printable document',
    'download.desc.png': 'Full resolution digital image',
    'download.preparing': 'Preparing...',
    'download.success': 'Complete',
    'editor.export.failed': 'Export failed',
    'editor.success.saved': 'Resume saved successfully',
    'editor.share': 'Share',
    'editor.share.link': 'Public link',
    'editor.share.copy': 'Copy Link',
    'editor.share.copied': 'Link copied to clipboard',
    'editor.share.failed': 'Publish failed',
    'share.modal.desc': 'Control how others access this resume',
    'share.status.public': 'Anyone with this link can view',
    'share.status.restricted': 'Private access (not public)',
    'share.settings.entry': 'Share settings',
    'share.visibility.public': 'Public',
    'share.visibility.restricted': 'Private',
    'share.settings.public': 'Public access',
    'share.settings.password': 'Password',
    'share.settings.passwordDesc': 'Require a code to view',
    'share.settings.passwordHint': 'Set a password (optional)',
    'share.settings.passwordHintHas': 'Password is set (enter to change)',
    'share.settings.passwordClear': 'Remove password',
    'share.settings.resetPassword': 'Reset',
    'share.settings.expiresAt': 'Expires at',
    'share.settings.expiresDesc': 'Link becomes invalid after this time',
    'share.settings.keepPasswordHint': 'Leave empty to keep current password',
    'share.settings.views': 'Views',
    'share.settings.lastAccessAt': 'Last access',
    'share.settings.save': 'Save settings',
    'share.settings.saved': 'Share settings saved',
    'share.settings.saveFailed': 'Failed to save share settings',
    'share.actions.disableLink': 'Make private',
    'common.resume': 'Resume',
    'template.basicInfo': 'Basic Information',
    'template.personalResume': 'Resume',
    'font.inter': 'Inter (Modern)',
    'font.roboto': 'Roboto (Technical)',
    'font.merriweather': 'Merriweather (Elegant)',
    'font.playfair': 'Playfair Display (Classy)',
    'font.mono': 'Roboto Mono (Code)',
    'font.yahei': '微软雅黑 (Microsoft YaHei)',
    'font.notosans': '思源黑体 (Noto Sans SC)',
    'font.simsun': '宋体 (SimSun)',
    'font.kaiti': '楷体 (KaiTi)',
    'dashboard.confirm.delete': 'Are you sure you want to delete this resume?',
    'dashboard.copySuffix': ' (Copy)',
    'settings.security': 'Security',
    'settings.saveChanges': 'Save Changes',
    'settings.updatePassword': 'Update Password',
    'settings.profile.photoLabel': 'Profile Photo',
    'settings.profile.changePhoto': 'Change Photo',
    'settings.profile.photoTip': 'JPG, GIF or PNG. Max size of 800K',
    'settings.displayName': 'Display Name',
    'settings.emailAddress': 'Email Address',
    'settings.emailChangeTip': 'Contact support to change email.',
    'settings.languagePreference': 'Language Preference',
    'settings.success.profileUpdated': 'Profile updated successfully.',
    'settings.success.passwordUpdated': 'Password updated successfully.'
    ,
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmNewPassword': 'Confirm New Password',
    'section.summary': 'Professional Summary',
    'section.experience': 'Work Experience',
    'section.education': 'Education',
    'section.skills': 'Skills',
    'section.projects': 'Projects',
    'section.internships': 'Internship Experience',
    'section.portfolio': 'Personal Works',
    'section.awards': 'Honors & Certificates',
    'section.interests': 'Interests & Hobbies',
    'section.jobApplication': 'Job Application',
    'section.exam': 'Exam Information',
    'section.selfEvaluation': 'Self Evaluation',
    'section.custom': 'Custom Section',
    'exam.school': 'Target School',
    'exam.major': 'Target Major',
    'exam.subject': 'Subject',
    'exam.score': 'Score',
    'exam.scoreLabel': 'Entrance Exam Scores',
    'exam.scoreType': 'Score Label',
    'exam.addScore': 'Add Course Score',
    'exam.placeholder.school': 'Enter target school',
    'exam.placeholder.major': 'Enter target major',
    'exam.placeholder.subject': 'Course name (e.g., English)',
    'exam.placeholder.score': 'Score (e.g., 80)',
    'exam.placeholder.scoreType': 'e.g., Entrance Exam',
    // Pricing
    'pricing.title': 'Pricing Plans',
    'pricing.subtitle': 'Simple, transparent pricing for everyone.',
    'pricing.basic': 'Basic',
    'pricing.pro': 'Pro',
    'pricing.basicDesc': 'Best for individuals.',
    'pricing.proDesc': 'Best for power users.',
    'pricing.price.free': '$0',
    'pricing.price.pro': '$0',
    'pricing.month': '/mo',
    'pricing.buy': 'Buy',
    'pricing.modal.title': 'Notice',
    'pricing.modal.planning': 'Free to use',
    'pricing.modal.close': 'Close'
    ,
    'nav.admin': 'Admin',
    'admin.title': 'Admin',
    'admin.backDashboard': 'Home',
    'admin.users': 'Users',
    'admin.resumes': 'Resumes',
    'admin.templates': 'Templates',
    'admin.shares': 'Shares',
    'admin.search': 'Search',
    'admin.keyword': 'Keyword',
    'admin.slugKeyword': 'Slug keyword',
    'admin.titleKeyword': 'Title keyword',
    'admin.columns.id': 'ID',
    'admin.columns.email': 'Email',
    'admin.columns.name': 'Name',
    'admin.columns.role': 'Role',
    'admin.columns.status': 'Status',
    'admin.columns.actions': 'Actions',
    'admin.columns.userDetails': 'User Details',
    'admin.columns.lastActivity': 'Last Activity',
    'admin.columns.user': 'User',
    'admin.columns.title': 'Title',
    'admin.columns.template': 'Template',
    'admin.columns.slug': 'Slug',
    'admin.columns.url': 'URL',
    'admin.status.active': 'Active',
    'admin.status.inactive': 'Inactive',
    'admin.filter.allStatuses': 'All Statuses',
    'admin.prev': 'Previous',
    'admin.next': 'Next',
    'admin.total': 'Total',
    'admin.pageSize': 'Page Size',
    'admin.actions.ban': 'Ban',
    'admin.actions.unban': 'Unban',
    'admin.actions.resetPassword': 'Reset Password',
    'admin.actions.delete': 'Delete',
    'admin.actions.transferOwner': 'Transfer Owner',
    'admin.actions.setPublic': 'Set Public',
    'admin.actions.setPrivate': 'Set Private',
    'admin.actions.create': 'Create',
    'admin.actions.update': 'Update',
    'admin.actions.preview': 'Preview',
    'admin.actions.export': 'Export Data',
    'admin.actions.addUser': 'Add New User',
    'admin.value.yes': 'Yes',
    'admin.value.no': 'No',
    'admin.msg.loadUsersFailed': 'Failed to load users.',
    'admin.msg.roleUpdated': 'Role updated.',
    'admin.msg.roleUpdateFailed': 'Failed to update role.',
    'admin.msg.banned': 'User banned.',
    'admin.msg.banFailed': 'Failed to ban user.',
    'admin.msg.unbanned': 'User unbanned.',
    'admin.msg.unbanFailed': 'Failed to unban user.',
    'admin.msg.newPassword': 'New password:',
    'admin.msg.resetFailed': 'Reset failed.',
    'admin.msg.loadResumesFailed': 'Failed to load resumes.',
    'admin.msg.deleted': 'Deleted.',
    'admin.msg.deleteFailed': 'Delete failed.',
    'admin.msg.transferred': 'Transferred.',
    'admin.msg.transferFailed': 'Transfer failed.',
    'admin.msg.setPublicSuccess': 'Set to public.',
    'admin.msg.setPublicFailed': 'Failed to set visibility.',
    'admin.msg.loadSharesFailed': 'Failed to load shares.',
    'admin.msg.visibilityUpdated': 'Visibility updated.',
    'admin.msg.visibilityUpdateFailed': 'Failed to update visibility.',
    'admin.msg.loadTemplatesFailed': 'Failed to load templates.',
    'admin.msg.templateCreated': 'Template created.',
    'admin.msg.templateCreateFailed': 'Failed to create template.',
    'admin.msg.templateUpdated': 'Template updated.',
    'admin.msg.templateUpdateFailed': 'Failed to update template.',
    'admin.msg.templateDeleted': 'Template deleted.',
    'admin.msg.templateDeleteFailed': 'Failed to delete template.',
    'admin.confirm.ban': 'Ban this user?',
    'admin.confirm.resetPassword': 'Reset password for this user?',
    'admin.confirm.deleteResume': 'Delete this resume?',
    'admin.confirm.setPublic': 'Set this resume to public?',
    'admin.confirm.deleteShare': 'Delete this share link?',
    'admin.input.newOwnerId': 'Enter new owner user ID',
    'admin.form.externalId': 'External ID',
    'admin.form.name': 'Name',
    'admin.form.nameZh': 'Chinese Name',
    'admin.form.nameEn': 'English Name',
    'admin.form.thumbnail': 'Thumbnail URL',
    'admin.form.category': 'Category',
    'admin.form.level': 'Level',
    'admin.form.usageCount': 'Usage Count',
    'admin.form.selectPlaceholder': 'Select...'
    ,
    'admin.form.multiSelect.searchPlaceholder': 'Search...',
    'admin.form.multiSelect.selectAll': 'Select all',
    'admin.form.multiSelect.unselectAll': 'Unselect all',
    'admin.form.multiSelect.availableSuffix': 'available',
    'admin.form.multiSelect.noResults': 'No results'
    ,
    'admin.validation.externalIdRequired': 'Please fill External ID',
    'admin.validation.nameRequired': 'Please provide Chinese or English name',
    'admin.menu.dashboard': 'Dashboard',
    'admin.menu.users': 'Users',
    'admin.menu.resumes': 'Resumes',
    'admin.menu.templates': 'Templates',
    'admin.menu.shares': 'Shares',
    'admin.menu.catalog': 'Jobs',
    'admin.menu.settings': 'Settings',
    'admin.templates.tab.templates': 'Templates',
    'admin.templates.tab.presets': 'Content Presets',
    'admin.templates.tab.variants': 'Resume Variants',
    'admin.msg.loadFailed': 'Failed to load.',
    'admin.msg.saveSuccess': 'Saved.',
    'admin.msg.saveFailed': 'Save failed.',
    'admin.msg.deleteSuccess': 'Deleted.',
    'admin.confirm.delete': 'Delete?',
    'admin.confirm.deleteMsg': 'This action cannot be undone.',
    'admin.confirm.clearJsonTitle': 'Clear JSON?',
    'admin.confirm.clearJsonMsg': 'This will clear the JSON editor. Continue?',
    'admin.catalog.tab.categories': 'Job Categories',
    'admin.catalog.tab.roles': 'Job Roles',
    'admin.catalog.tab.jobs': 'Jobs',
    'admin.catalog.tab.presets': 'Content Presets',
    'admin.catalog.tab.variants': 'Template Variants',
    'admin.catalog.jobs.name': 'Job',
    'admin.catalog.jobs.stats': 'Stats',
    'admin.catalog.actions.addRole': 'Add role',
    'admin.catalog.actions.addSubcategory': 'Add subcategory',
    'admin.catalog.actions.expandAll': 'Expand all',
    'admin.catalog.actions.collapseAll': 'Collapse all',
    'admin.catalog.actions.expand': 'Expand',
    'admin.catalog.actions.collapse': 'Collapse',
    'admin.catalog.actions.formatJson': 'Format JSON',
    'admin.catalog.actions.minifyJson': 'Minify',
    'admin.catalog.actions.copyJson': 'Copy',
    'admin.catalog.actions.copied': 'Copied',
    'admin.catalog.actions.clearJson': 'Clear',
    'admin.catalog.empty': 'No data',
    'admin.catalog.emptyDesc': 'Click Create to add your first item.',
    'admin.catalog.jobs.subcategories': 'subcategories',
    'admin.catalog.jobs.roles': 'roles',
    'admin.catalog.jobs.ungrouped': 'Ungrouped',
    'admin.catalog.section.basic': 'Basic Info',
    'admin.catalog.section.config': 'Configuration',
    'admin.catalog.section.data': 'Data',
    'admin.catalog.form.parent': 'Parent',
    'admin.catalog.form.order': 'Order',
    'admin.catalog.form.active': 'Active',
    'admin.catalog.form.category': 'Category',
    'admin.catalog.form.language': 'Language',
    'admin.catalog.form.role': 'Role',
    'admin.catalog.form.preset': 'Preset',
    'admin.catalog.form.template': 'Layout Template',
    'admin.catalog.form.dataJson': 'Preset JSON',
    'admin.catalog.form.dataJsonPlaceholder': 'Paste or type JSON here...',
    'admin.catalog.none': 'None',
    'admin.catalog.msg.invalidJson': 'Invalid JSON',
    'admin.catalog.msg.jsonOk': 'JSON ok',
    'admin.catalog.msg.jsonEmptyHint': 'Empty',
    'admin.catalog.stats.characters': 'Characters',
    'admin.catalog.stats.lines': 'Lines',
    'admin.catalog.generate.title': 'Generate variants',
    'admin.catalog.generate.modeSingle': 'Single create',
    'admin.catalog.generate.modeSkip': 'Skip existing',
    'admin.catalog.generate.modeUpdate': 'Update existing',
    'admin.catalog.generate.namePrefix': 'Name prefix',
    'admin.catalog.generate.submit': 'Generate',
    'admin.catalog.generate.done': 'Generate done',
    'admin.catalog.generate.failed': 'Generate failed',
    'admin.catalog.generate.result': 'Generate result',
    'admin.catalog.generate.created': 'Created',
    'admin.catalog.generate.updated': 'Updated',
    'admin.catalog.generate.skipped': 'Skipped',
    'admin.catalog.generate.failedCount': 'Failed',
    'admin.catalog.generate.action': 'Action',
    'admin.catalog.generate.error': 'Error',
    'admin.catalog.enabled': 'Enabled',
    'admin.catalog.disabled': 'Disabled',
    'admin.catalog.yes': 'Yes',
    'admin.catalog.no': 'No',
    'admin.pagination.total': 'Total',
    'admin.pagination.prev': 'Prev',
    'admin.pagination.next': 'Next',
    'admin.stats.trend': 'Trend',
    'admin.stats.totals': 'Totals',
    'admin.stats.users': 'Registered Users',
    'admin.stats.resumes': 'New Resumes',
    'admin.stats.templates': 'Templates',
    'admin.stats.visitors': 'Visitors',
    'admin.stats.templateTrend': 'Template Trend',
    'admin.stats.generated': 'Generated',
    'admin.config.tab.general': 'General',
    'admin.config.tab.smtp': 'SMTP',
    'admin.config.tab.wechat': 'WeChat',
    'admin.config.tab.github': 'GitHub',
    'admin.config.tab.other': 'Other',
    'admin.config.tab.oauth': 'Third-Party Login',
    'admin.config.msg.loadFailed': 'Failed to load configs.',
    'admin.config.msg.saveSuccess': 'Configs saved successfully.',
    'admin.config.msg.saveFailed': 'Failed to save configs.',
    'admin.config.key.enableEmailVerification': 'Enable Email Verification',
    'admin.config.key.enableWeChatLogin': 'Enable WeChat Login',
    'admin.config.key.enableGithubLogin': 'Enable GitHub Login',
    'admin.config.key.wechatAppId': 'WeChat App ID',
    'admin.config.key.githubClientId': 'GitHub Client ID',
    'admin.config.key.githubClientSecret': 'GitHub Client Secret',
    'admin.config.key.githubRedirectUri': 'GitHub Redirect URI',
    'admin.config.key.smtpHost': 'SMTP Host',
    'admin.config.key.smtpPort': 'SMTP Port',
    'admin.config.key.smtpUser': 'SMTP User',
    'admin.config.key.smtpPass': 'SMTP Password',
    'admin.config.key.smtpFromName': 'SMTP From Name',
    'admin.config.key.smtpSecure': 'SMTP Secure',
    'admin.config.key.oauthAllowedOrigins': 'OAuth Allowed Origins',
    'admin.config.key.enablePricingPage': 'Enable Pricing Page',
    'admin.config.tab.storage': 'Storage',
    'admin.config.tab.chrome': 'Chrome',
    'admin.config.tab.security': 'Security',
    'admin.config.key.storageS3Enabled': 'Enable S3 storage',
    'admin.config.key.storageS3Bucket': 'S3 Bucket',
    'admin.config.key.storageS3Region': 'S3 Region',
    'admin.config.key.storageS3Endpoint': 'S3 Endpoint',
    'admin.config.key.storageS3AccessKey': 'S3 Access Key',
    'admin.config.key.storageS3SecretKey': 'S3 Secret Key',
    'admin.config.key.chromeApiUrl': 'Chrome API URL'
    ,
    'admin.config.key.corsOrigins': 'CORS Allowed Origins',
    'admin.config.key.frontendBaseUrl': 'Frontend Base URL'
  },
  zh: {
    'nav.templates': '模板库',
    'nav.dashboard': '我的简历',
    'nav.pricing': '订阅方案',
    'nav.signin': '登录',
    'nav.getStarted': '开始制作',
    'nav.signout': '退出登录',
    'nav.settings': '账号设置',
    'nav.profile': '个人资料',
    'hero.title': '打造您的完美简历',
    'hero.subtitle': 'AI 智能辅助',
    'hero.desc': '几分钟内构建专业、通过 ATS 筛选的简历。选择精选模板，使用 AI 润色文本，助您斩获理想 Offer。',
    'hero.cta': '创建简历',
    'hero.cta_secondary': '我的简历',
    'home.popular': '热门模板',
    'home.quickAccess': '快速入口',
    'common.edit': '编辑',
    'common.share': '分享',
    'common.preview': '预览',
    'common.duplicate': '创建副本',
    'common.delete': '删除',
    'common.rename': '重命名',
    'common.save': '保存',
    'common.download': '下载',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.confirmAction': '确认操作',
    'common.close': '关闭',
    'common.refresh': '刷新',
    'common.loading': '加载中...',
    'common.copied': '已复制',
    'common.copyFailed': '复制失败',
    'editor.content': '内容编辑',
    'editor.design': '外观设计',
    'editor.personal': '个人信息',
    'editor.theme': '主题设置',
    'editor.font': '字体选择',
    'editor.spacing': '间距与密度',
    'editor.color': '主题颜色',
    'editor.ai_polish': 'AI 润色',
    'dashboard.title': '我的简历',
    'dashboard.createNew': '新建简历',
    'templates.title': '简历模板库',
    'templates.desc': '选择一个专业设计的模板，开始您的求职之旅。',
    'templates.sidebar.navLabel': '岗位分类导航',
    'templates.hero.title': '发现你的完美简历',
    'templates.hero.desc': '从大量专业设计的模板与岗位变体中挑选，助你脱颖而出。',
    'templates.filter.industry': '行业分类',
    'templates.filter.jobCategory': '岗位分类',
    'templates.filter.jobRole': '岗位方向',
    'templates.filter.level': '职级经验',
    'templates.search': '搜索模板...',
    'templates.actions.search': '搜索',
    'templates.sort.latest': '最新',
    'templates.sort.hot': '最热',
    'templates.hotSearch': '热门搜索:',
    'footer.rights': '版权所有。',
    // Auth
    'auth.welcome': '欢迎回来',
    'auth.welcomeDesc': '输入您的账号信息以登录',
    'auth.orContinueWith': '或使用以下方式继续',
    'auth.provider.github': 'GitHub',
    'auth.provider.wechat': '微信',
    'auth.createAccount': '创建新账号',
    'auth.createDesc': '输入邮箱以开始注册流程',
    'auth.email': '电子邮箱',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.verificationCode': '验证码',
    'auth.sendCode': '获取验证码',
    'auth.sending': '发送中...',
    'auth.resend': '发送验证码',
    'auth.login': '登录',
    'auth.register': '注册',
    'auth.noAccount': "还没有账号？",
    'auth.hasAccount': '已有账号？',
    'auth.forgotPassword': '忘记密码？',
    'auth.terms': '点击注册即表示您同意我们的服务条款和隐私政策。',
    'auth.error.invalidEmail': '请输入有效的电子邮箱地址。',
    'auth.error.passwordMismatch': '两次输入的密码不一致。',
    'auth.error.invalidCode': '验证码错误（测试码：123456）。',
    'auth.success.codeSent': '验证码已发送至您的邮箱。',
    'auth.quote': '成功不是终点，失败也非末日：关键在于继续前行的勇气。',
    'auth.quoteAuthor': '温斯顿·丘吉尔',
    'auth.placeholder.email': 'you@example.com',
    'auth.placeholder.code': '123456',
    'auth.placeholder.password': '••••••••',
    'auth.placeholder.passwordMin': '至少 6 个字符',
    'auth.placeholder.reenterPassword': '请再次输入密码',
    'auth.error.fillAll': '请填写所有字段',
    'auth.error.invalidCredentials': '邮箱或密码不正确',
    'auth.error.general': '发生错误，请稍后重试。',
    'auth.error.sendCodeFailed': '验证码发送失败。',
    'auth.error.passwordTooShort': '密码至少需要 6 个字符。',
    'auth.error.registrationFailed': '注册失败。',
    'common.backHome': '返回首页',
    'footer.product': '产品',
    'footer.legal': '法律',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.language': '语言',
    'lang.en': '英文',
    'lang.zh': '中文',
    'lang.en_short': 'EN',
    'lang.zh_short': '中',
    'lang.switchToZh': '切换为中文',
    'lang.switchToEn': '切换为英文',
    'lang.switchTitle': '切换语言',
    'a11y.openUserMenu': '打开用户菜单',
    'a11y.signedInAs': '当前登录为',
    'a11y.authBackgroundAlt': '认证背景图',
    'a11y.avatarAlt': '头像',
    'a11y.drag': '拖拽',
    'a11y.removePhoto': '移除照片',
    'home.actions.viewAll': '查看全部',
    'home.actions.useTemplate': '使用模板',
    'home.quick.it': 'IT / 科技',
    'home.quick.finance': '金融',
    'home.quick.creative': '创意',
    'home.quick.student': '学生',
    'home.hero.alt': '简历规划',
    'features.title': '功能特性',
    'features.subtitle': '助你高效拿到心仪工作',
    'features.ai.title': 'AI 写作与润色',
    'features.ai.desc': '写作无从下笔？使用 Gemini 驱动的 AI 即刻生成总结并优化要点。',
    'features.ats.title': 'ATS 友好模板',
    'features.ats.desc': '模板专为通过候选人追踪系统设计，确保你的简历到达人眼。',
    'features.share.title': '在线分享',
    'features.share.desc': '发布唯一链接，追踪访问量，并可直接分享到 LinkedIn 或二维码。',
    'features.preview.title': '实时预览',
    'features.preview.desc': '输入即刻看到变化，拖拽分区轻松重组你的经历。',
    'preview.pagesHint': '预计分页：共 {count} 页',
    'preview.pageBreakTip.badge': '分页小贴士',
    'preview.pageBreakTip.modalTitle': '分页小贴士',
    'preview.pageBreakTip.modalDesc': '此处为分页栏，用于提示预览的分页位置。若内容被分页栏遮挡，可在上方按回车换行，或适当调整字号/间距。',
    'preview.pageBreakTip.close': '关闭',
    'public.unavailable.title': '链接不可用',
    'public.unavailable.desc': '该简历的公开分享已关闭或链接已失效。',
    'public.expired.title': '链接已过期',
    'public.expired.desc': '该分享链接已过期。',
    'public.password.title': '需要密码',
    'public.password.desc': '请输入密码以查看该简历。',
    'public.password.placeholder': '密码',
    'public.password.submit': '解锁',
    'public.password.invalid': '密码不正确。',
    'rte.tooltip.bold': '加粗',
    'rte.tooltip.italic': '斜体',
    'rte.tooltip.bullets': '项目符号',
    'rte.tooltip.undo': '撤销',
    'rte.tooltip.redo': '重做',
    'templates.filters.label': '筛选：',
    'templates.actions.useTemplate': '使用模板',
    'templates.actions.clearAll': '清空',
    'templates.actions.clearFilters': '清除筛选',
    'templates.meta.usageCount': '使用次数',
    'templates.empty': '没有符合条件的模板。',
    'templates.category.all': '全部',
    'templates.category.IT': 'IT',
    'templates.category.Finance': '金融',
    'templates.category.Creative': '创意',
    'templates.category.General': '通用',
    'templates.level.all': '全部',
    'templates.level.Intern': '实习',
    'templates.level.Junior': '初级',
    'templates.level.Senior': '高级',
    'templates.level.Executive': '管理层',
    'editor.profile.label': '个人照片',
    'editor.profile.upload': '上传照片',
    'editor.profile.change': '更换照片',
    'editor.profile.tipMaxSize': '最大 2MB（JPG/PNG）。',
    'editor.fields.fullName': '姓名',
    'editor.fields.jobTitle': '职位',
    'editor.fields.email': '邮箱',
    'editor.fields.phone': '电话',
    'editor.fields.website': '网站/领英',
    'editor.fields.gender': '性别',
    'editor.fields.age': '年龄',
    'editor.fields.degree': '学历',
    'editor.fields.jobApplication': '求职岗位',
    'editor.fields.city': '意向城市',
    'editor.fields.expectedSalary': '期望薪资',
    'editor.fields.joinTime': '入职时间',
    'editor.customInfo.title': '自定义信息',
    'editor.customInfo.add': '添加自定义信息',
    'editor.customInfo.label': '名称',
    'editor.customInfo.value': '内容',
    'editor.placeholder.titleExample': '标题（如：资深经理）',
    'editor.placeholder.subtitleExample': '副标题（如：公司）',
    'editor.placeholder.dateRange': '时间范围',
    'editor.placeholder.major': '专业',
    'editor.placeholder.degree': '学位',
    'editor.placeholder.skills': '在此列出技能...',
    'editor.placeholder.achievements': '描述你的成就...',
    'editor.labels.experience.title': '经历名称',
    'editor.labels.experience.role': '你的角色',
    'editor.labels.projects.title': '项目名称',
    'editor.labels.projects.role': '你的角色',
    'editor.labels.education.school': '学校名称',
    'editor.labels.education.department': '院系/学院（可选）',
    'editor.labels.education.major': '所学专业',
    'editor.labels.education.degree': '学历',
    'editor.labels.internships.company': '公司名称',
    'editor.labels.common.startDate': '开始时间',
    'editor.labels.common.endDate': '结束时间',
    'editor.labels.common.description': '内容',
    'editor.ai.polishing': '润色中...',
    'editor.error.imageTooLarge': '图片过大，请上传小于 2MB 的图片。',
    'editor.addItem': '添加条目',
    'editor.font.group.englishSans': '英文 - 无衬线',
    'editor.font.group.englishSerif': '英文 - 衬线',
    'editor.font.group.englishMono': '英文 - 等宽',
    'editor.font.group.chineseSans': '中文 - 黑体',
    'editor.font.group.chineseSerif': '中文 - 宋体/楷体',
    'editor.font.note': '中文字体依赖系统或支持的网页字体。',
    'editor.spacing.option.compact': '紧凑（信息更多）',
    'editor.spacing.option.normal': '正常（均衡）',
    'editor.spacing.option.spacious': '宽松（清爽）',
    'editor.color.customTitle': '自定义颜色',
    'editor.fontSize': '文字大小',
    'editor.back': '返回',
    'editor.addSection': '添加自定义模块',
    'editor.removeSection': '删除这个模块',
    'editor.rename': '重命名模块',
    'editor.toggleVisibility': '切换显示',
    'editor.template': '切换模板',
    'editor.actions.changeTemplate': '更换模板',
    'editor.language': '语言',
    'editor.language.select': '选择语言',
    'editor.save': '保存',
    'editor.export.pdf': '导出 PDF',
    'editor.export.png': '导出图片',
    'download.selectFormat': '选择导出格式',
    'download.desc.pdf': '高质量可打印文档',
    'download.desc.png': '全分辨率数字图片',
    'download.preparing': '准备中...',
    'download.success': '完成',
    'editor.export.failed': '导出失败',
    'editor.success.saved': '简历保存成功',
    'editor.share': '分享',
    'editor.share.link': '公开链接',
    'editor.share.copy': '复制链接',
    'editor.share.copied': '链接已复制到剪贴板',
    'editor.share.failed': '发布失败',
    'share.modal.desc': '控制他人如何访问这份简历',
    'share.status.public': '任何拥有链接的人都可查看',
    'share.status.restricted': '当前为私密访问（未公开）',
    'share.settings.entry': '分享设置',
    'share.visibility.public': '公开',
    'share.visibility.restricted': '私密',
    'share.settings.public': '公开访问',
    'share.settings.password': '访问密码',
    'share.settings.passwordDesc': '需要密码才能访问',
    'share.settings.passwordHint': '设置密码（可选）',
    'share.settings.passwordHintHas': '已设置密码（输入可更改）',
    'share.settings.passwordClear': '移除密码',
    'share.settings.resetPassword': '重设密码',
    'share.settings.expiresAt': '有效期至',
    'share.settings.expiresDesc': '到期后链接将失效',
    'share.settings.keepPasswordHint': '留空表示保留原密码',
    'share.settings.views': '访问量',
    'share.settings.lastAccessAt': '最近访问',
    'share.settings.save': '保存设置',
    'share.settings.saved': '分享设置已保存',
    'share.settings.saveFailed': '分享设置保存失败',
    'share.actions.disableLink': '设为私密',
    'common.resume': '简历',
    'template.basicInfo': '基本信息',
    'template.personalResume': '个人简历',
    'font.inter': 'Inter (现代)',
    'font.roboto': 'Roboto (技术)',
    'font.merriweather': 'Merriweather (优雅)',
    'font.playfair': 'Playfair Display (经典)',
    'font.mono': 'Roboto Mono (代码)',
    'font.yahei': '微软雅黑 (Microsoft YaHei)',
    'font.notosans': '思源黑体 (Noto Sans SC)',
    'font.simsun': '宋体 (SimSun)',
    'font.kaiti': '楷体 (KaiTi)',
    'dashboard.confirm.delete': '确定要删除这份简历吗？',
    'dashboard.copySuffix': '（副本）',
    'common.toPresent': '至今',
    'settings.security': '安全',
    'settings.saveChanges': '保存更改',
    'settings.updatePassword': '更新密码',
    'settings.profile.photoLabel': '个人照片',
    'settings.profile.changePhoto': '更换照片',
    'settings.profile.photoTip': 'JPG、GIF 或 PNG。最大 800K',
    'settings.displayName': '显示名称',
    'settings.emailAddress': '电子邮箱',
    'settings.emailChangeTip': '如需更改邮箱请联系支持。',
    'settings.languagePreference': '语言偏好',
    'settings.success.profileUpdated': '资料更新成功。',
    'settings.success.passwordUpdated': '密码更新成功。',
    'settings.currentPassword': '当前密码',
    'settings.newPassword': '新密码',
    'settings.confirmNewPassword': '确认新密码',
    'section.summary': '个人总结',
    'section.experience': '工作经历',
    'section.education': '教育背景',
    'section.skills': '技能特长',
    'section.projects': '项目经历',
    'section.internships': '实习经验',
    'section.portfolio': '个人作品',
    'section.awards': '荣誉证书',
    'section.interests': '兴趣爱好',
    'section.jobApplication': '求职岗位',
    'section.exam': '报考信息',
    'section.selfEvaluation': '自我评价',
    'section.custom': '自定义模块',
    'exam.school': '报考院校',
    'exam.major': '报考专业',
    'exam.subject': '课程',
    'exam.score': '成绩',
    'exam.scoreLabel': '考研成绩',
    'exam.scoreType': '成绩标题',
    'exam.addScore': '添加课程成绩',
    'exam.placeholder.school': '填写报考学校',
    'exam.placeholder.major': '填写报考专业',
    'exam.placeholder.subject': '课程名称，例如：英语',
    'exam.placeholder.score': '课程成绩，例如：80',
    'exam.placeholder.scoreType': '例如：考研成绩',
    // Pricing
    'pricing.title': '订阅方案',
    'pricing.subtitle': '简单透明的定价方案。',
    'pricing.basic': '基础版',
    'pricing.pro': '专业版',
    'pricing.basicDesc': '适合个人使用。',
    'pricing.proDesc': '适合资深用户。',
    'pricing.price.free': '¥0',
    'pricing.price.pro': '¥0',
    'pricing.month': '/月',
    'pricing.buy': '购买',
    'pricing.modal.title': '提示',
    'pricing.modal.planning': '免费使用',
    'pricing.modal.close': '关闭'
    ,
    'nav.admin': '管理后台',
    'admin.title': '管理后台',
    'admin.backDashboard': '首页',
    'admin.users': '用户',
    'admin.resumes': '简历',
    'admin.templates': '模板',
    'admin.shares': '分享',
    'admin.search': '搜索',
    'admin.keyword': '关键字',
    'admin.slugKeyword': 'Slug 关键字',
    'admin.titleKeyword': '标题关键字',
    'admin.columns.id': 'ID',
    'admin.columns.email': '邮箱',
    'admin.columns.name': '姓名',
    'admin.columns.role': '角色',
    'admin.columns.status': '状态',
    'admin.columns.actions': '操作',
    'admin.columns.userDetails': '用户详情',
    'admin.columns.lastActivity': '最近活动',
    'admin.columns.user': '用户',
    'admin.columns.title': '标题',
    'admin.columns.template': '模板',
    'admin.columns.slug': 'Slug',
    'admin.columns.url': '链接',
    'admin.status.active': '启用',
    'admin.status.inactive': '禁用',
    'admin.prev': '上一页',
    'admin.next': '下一页',
    'admin.total': '共',
    'admin.filter.allStatuses': '全部状态',
    'admin.pageSize': '每页',
    'admin.actions.ban': '封禁',
    'admin.actions.unban': '解禁',
    'admin.actions.resetPassword': '重置密码',
    'admin.actions.delete': '删除',
    'admin.actions.transferOwner': '转移所有者',
    'admin.actions.setPublic': '设为公开',
    'admin.actions.setPrivate': '设为私密',
    'admin.actions.create': '创建',
    'admin.actions.update': '更新',
    'admin.actions.preview': '预览',
    'admin.actions.export': '导出数据',
    'admin.actions.addUser': '新增用户',
    'admin.value.yes': '是',
    'admin.value.no': '否',
    'admin.msg.loadUsersFailed': '无法获取用户列表。',
    'admin.msg.roleUpdated': '角色已更新。',
    'admin.msg.roleUpdateFailed': '更新角色失败。',
    'admin.msg.banned': '已封禁。',
    'admin.msg.banFailed': '封禁失败。',
    'admin.msg.unbanned': '已解禁。',
    'admin.msg.unbanFailed': '解禁失败。',
    'admin.msg.newPassword': '新密码：',
    'admin.msg.resetFailed': '重置失败。',
    'admin.msg.loadResumesFailed': '无法获取简历列表。',
    'admin.msg.deleted': '已删除。',
    'admin.msg.deleteFailed': '删除失败。',
    'admin.msg.transferred': '已转移。',
    'admin.msg.transferFailed': '转移失败。',
    'admin.msg.setPublicSuccess': '已公开。',
    'admin.msg.setPublicFailed': '设置失败。',
    'admin.msg.loadSharesFailed': '无法获取分享列表。',
    'admin.msg.visibilityUpdated': '已更新公开性。',
    'admin.msg.visibilityUpdateFailed': '更新失败。',
    'admin.msg.loadTemplatesFailed': '无法获取模板列表。',
    'admin.msg.templateCreated': '模板已创建。',
    'admin.msg.templateCreateFailed': '创建失败。',
    'admin.msg.templateUpdated': '模板已更新。',
    'admin.msg.templateUpdateFailed': '更新失败。',
    'admin.msg.templateDeleted': '模板已删除。',
    'admin.msg.templateDeleteFailed': '删除失败。',
    'admin.confirm.ban': '确认封禁该用户？',
    'admin.confirm.resetPassword': '为该用户重置密码？',
    'admin.confirm.deleteResume': '确认删除该简历？',
    'admin.confirm.setPublic': '将该简历设为公开？',
    'admin.confirm.deleteShare': '确认删除该分享链接？',
    'admin.input.newOwnerId': '请输入新的所有者用户 ID',
    'admin.form.externalId': 'External ID',
    'admin.form.name': '名称',
    'admin.form.nameZh': '中文名',
    'admin.form.nameEn': '英文名',
    'admin.form.thumbnail': '缩略图 URL',
    'admin.form.category': '分类',
    'admin.form.level': '等级',
    'admin.form.usageCount': '使用次数',
    'admin.form.selectPlaceholder': '请选择'
    ,
    'admin.form.multiSelect.searchPlaceholder': '搜索...',
    'admin.form.multiSelect.selectAll': '全选',
    'admin.form.multiSelect.unselectAll': '取消全选',
    'admin.form.multiSelect.availableSuffix': '可选',
    'admin.form.multiSelect.noResults': '没有匹配结果'
    ,
    'admin.validation.externalIdRequired': '请填写 External ID',
    'admin.validation.nameRequired': '请至少填写中文名或英文名',
    'admin.menu.dashboard': '面板',
    'admin.menu.users': '用户',
    'admin.menu.resumes': '简历',
    'admin.menu.templates': '模板',
    'admin.menu.shares': '分享',
    'admin.menu.catalog': '岗位',
    'admin.menu.settings': '参数',
    'admin.templates.tab.templates': '模版本体',
    'admin.templates.tab.presets': '内容预设',
    'admin.templates.tab.variants': '简历变体',
    'admin.msg.loadFailed': '加载失败。',
    'admin.msg.saveSuccess': '保存成功。',
    'admin.msg.saveFailed': '保存失败。',
    'admin.msg.deleteSuccess': '删除成功。',
    'admin.confirm.delete': '确认删除？',
    'admin.confirm.deleteMsg': '此操作不可撤销。',
    'admin.confirm.clearJsonTitle': '确认清空？',
    'admin.confirm.clearJsonMsg': '将清空 JSON 编辑器内容，此操作不可撤销。',
    'admin.catalog.tab.categories': '岗位',
    'admin.catalog.tab.roles': '岗位方向',
    'admin.catalog.tab.jobs': '岗位',
    'admin.catalog.tab.presets': '内容预设',
    'admin.catalog.tab.variants': '模板变体',
    'admin.catalog.jobs.name': '岗位',
    'admin.catalog.jobs.stats': '统计',
    'admin.catalog.actions.addRole': '新增岗位方向',
    'admin.catalog.actions.addSubcategory': '新增小分类',
    'admin.catalog.actions.expandAll': '全部展开',
    'admin.catalog.actions.collapseAll': '全部收起',
    'admin.catalog.actions.expand': '展开',
    'admin.catalog.actions.collapse': '收起',
    'admin.catalog.actions.formatJson': '格式化 JSON',
    'admin.catalog.actions.minifyJson': '压缩',
    'admin.catalog.actions.copyJson': '复制',
    'admin.catalog.actions.copied': '已复制',
    'admin.catalog.actions.clearJson': '清空',
    'admin.catalog.empty': '暂无数据',
    'admin.catalog.emptyDesc': '点击右上角创建开始新增',
    'admin.catalog.jobs.subcategories': '小类',
    'admin.catalog.jobs.roles': '岗位',
    'admin.catalog.jobs.ungrouped': '未分组',
    'admin.catalog.section.basic': '基础信息',
    'admin.catalog.section.config': '配置',
    'admin.catalog.section.data': '数据',
    'admin.catalog.form.parent': '父级分类',
    'admin.catalog.form.order': '排序',
    'admin.catalog.form.active': '启用',
    'admin.catalog.form.category': '岗位',
    'admin.catalog.form.language': '语言',
    'admin.catalog.form.role': '岗位方向',
    'admin.catalog.form.preset': '内容预设',
    'admin.catalog.form.template': '布局模板',
    'admin.catalog.form.dataJson': '预设 JSON',
    'admin.catalog.form.dataJsonPlaceholder': '粘贴或输入 JSON...',
    'admin.catalog.none': '无',
    'admin.catalog.msg.invalidJson': 'JSON 格式不正确',
    'admin.catalog.msg.jsonOk': 'JSON 正常',
    'admin.catalog.msg.jsonEmptyHint': '为空',
    'admin.catalog.stats.characters': '字符数',
    'admin.catalog.stats.lines': '行数',
    'admin.catalog.generate.title': '批量生成变体',
    'admin.catalog.generate.modeSingle': '单个创建',
    'admin.catalog.generate.modeSkip': '已存在则跳过',
    'admin.catalog.generate.modeUpdate': '已存在则更新',
    'admin.catalog.generate.namePrefix': '名称前缀',
    'admin.catalog.generate.submit': '生成',
    'admin.catalog.generate.done': '生成完成',
    'admin.catalog.generate.failed': '生成失败',
    'admin.catalog.generate.result': '生成结果',
    'admin.catalog.generate.created': '新增',
    'admin.catalog.generate.updated': '更新',
    'admin.catalog.generate.skipped': '跳过',
    'admin.catalog.generate.failedCount': '失败',
    'admin.catalog.generate.action': '动作',
    'admin.catalog.generate.error': '错误',
    'admin.catalog.enabled': '启用',
    'admin.catalog.disabled': '停用',
    'admin.catalog.yes': '是',
    'admin.catalog.no': '否',
    'admin.pagination.total': '总计',
    'admin.pagination.prev': '上一页',
    'admin.pagination.next': '下一页',
    'admin.stats.trend': '趋势',
    'admin.stats.totals': '总计',
    'admin.stats.users': '注册用户',
    'admin.stats.resumes': '新增简历',
    'admin.stats.templates': '模板',
    'admin.stats.visitors': '访客',
    'admin.stats.templateTrend': '模板趋势',
    'admin.stats.generated': '生成于',
    'admin.config.tab.general': '通用',
    'admin.config.tab.smtp': 'SMTP',
    'admin.config.tab.wechat': '微信',
    'admin.config.tab.github': 'GitHub',
    'admin.config.tab.other': '其他',
    'admin.config.tab.oauth': '三方登录',
    'admin.config.msg.loadFailed': '无法加载参数。',
    'admin.config.msg.saveSuccess': '参数保存成功。',
    'admin.config.msg.saveFailed': '保存参数失败。',
    'admin.config.key.enableEmailVerification': '启用邮箱验证码',
    'admin.config.key.enableWeChatLogin': '启用微信登录',
    'admin.config.key.enableGithubLogin': '启用 GitHub 登录',
    'admin.config.key.wechatAppId': '微信 AppID',
    'admin.config.key.wechatAppSecret': '微信 AppSecret',
    'admin.config.key.wechatRedirectUri': '微信回调地址',
    'admin.config.key.githubClientId': 'GitHub Client ID',
    'admin.config.key.githubClientSecret': 'GitHub Client Secret',
    'admin.config.key.githubRedirectUri': 'GitHub 回调地址',
    'admin.config.key.smtpHost': 'SMTP 主机',
    'admin.config.key.smtpPort': 'SMTP 端口',
    'admin.config.key.smtpUser': 'SMTP 用户名',
    'admin.config.key.smtpPass': 'SMTP 密码',
    'admin.config.key.smtpFromName': 'SMTP 发件人名称',
    'admin.config.key.smtpSecure': 'SMTP 安全连接',
    'admin.config.key.oauthAllowedOrigins': 'OAuth 允许来源',
    'admin.config.key.enablePricingPage': '展示订阅方案页面',
    'admin.config.tab.storage': '存储配置',
    'admin.config.tab.chrome': 'Chrome',
    'admin.config.tab.security': '安全',
    'admin.config.key.storageS3Enabled': '启用 S3 存储',
    'admin.config.key.storageS3Bucket': 'S3 存储桶',
    'admin.config.key.storageS3Region': 'S3 区域',
    'admin.config.key.storageS3Endpoint': 'S3 端点（可选）',
    'admin.config.key.storageS3AccessKey': 'S3 访问键（可选）',
    'admin.config.key.storageS3SecretKey': 'S3 密钥（可选）',
    'admin.config.key.chromeApiUrl': 'Chrome API 地址',
    'admin.config.key.corsOrigins': 'CORS 允许来源',
    'admin.config.key.frontendBaseUrl': '前端基础地址'
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode; languageOverride?: Language }> = ({ children, languageOverride }) => {
  const [languageState, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('lang') as Language | null;
    return saved || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('lang', lang);
  };

  const t = (key: string): string => {
    const usedLang = languageOverride || languageState;
    return translations[usedLang][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language: languageOverride || languageState, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
