import React, { createContext, useContext, useState, ReactNode } from 'react';
import { Language } from '../types';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    'nav.templates': 'Templates',
    'nav.dashboard': 'My Resumes',
    'nav.pricing': 'Pricing',
    'nav.signin': 'Sign In',
    'nav.getStarted': 'Get Started',
    'nav.signout': 'Sign Out',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    'hero.title': 'Craft your perfect resume',
    'hero.subtitle': 'with AI precision',
    'hero.desc': 'Build professional, ATS-friendly resumes in minutes. Choose from our curated templates, use AI to polish your text, and land your dream job.',
    'hero.cta': 'Create Resume',
    'hero.cta_secondary': 'My Resumes',
    'home.popular': 'Popular Templates',
    'home.quickAccess': 'Quick Access',
    'common.edit': 'Edit',
    'common.preview': 'Preview',
    'common.duplicate': 'Duplicate',
    'common.delete': 'Delete',
    'common.rename': 'Rename',
    'common.save': 'Save',
    'common.download': 'Download',
    'editor.content': 'Content',
    'editor.design': 'Design',
    'editor.personal': 'Personal Information',
    'editor.theme': 'Theme Settings',
    'editor.font': 'Font Family',
    'editor.spacing': 'Spacing & Density',
    'editor.color': 'Accent Color',
    'editor.ai_polish': 'AI Polish',
    'dashboard.title': 'My Resumes',
    'dashboard.createNew': 'Create New Resume',
    'templates.title': 'Resume Templates',
    'templates.desc': 'Choose a professionally designed template to get started.',
    'templates.filter.industry': 'Industry',
    'templates.filter.level': 'Level',
    'templates.search': 'Search templates...',
    'footer.rights': 'All rights reserved.',
    // Auth
    'auth.welcome': 'Welcome back',
    'auth.welcomeDesc': 'Enter your details to access your account.',
    'auth.createAccount': 'Create an account',
    'auth.createDesc': 'Enter your email to get started.',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.verificationCode': 'Verification Code',
    'auth.sendCode': 'Send Code',
    'auth.sending': 'Sending...',
    'auth.resend': 'Resend in',
    'auth.login': 'Sign In',
    'auth.register': 'Sign Up',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.forgotPassword': 'Forgot password?',
    'auth.terms': 'By clicking continue, you agree to our Terms of Service and Privacy Policy.',
    'auth.error.invalidEmail': 'Please enter a valid email.',
    'auth.error.passwordMismatch': 'Passwords do not match.',
    'auth.error.invalidCode': 'Invalid verification code.',
    'auth.success.codeSent': 'Verification code sent to your email.',
    'auth.placeholder.email': 'you@example.com',
    'auth.placeholder.code': '123456',
    'auth.placeholder.passwordMin': 'Min 6 characters',
    'auth.placeholder.reenterPassword': 'Re-enter password',
    'auth.error.fillAll': 'Please fill in all fields',
    'auth.error.invalidCredentials': 'Invalid email or password',
    'auth.error.general': 'An error occurred. Please try again.',
    'auth.error.sendCodeFailed': 'Failed to send code.',
    'auth.error.passwordTooShort': 'Password must be at least 6 characters.',
    'auth.error.registrationFailed': 'Registration failed.',
    'common.backHome': 'Back to Home',
    'footer.product': 'Product',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.language': 'Language',
    'lang.en': 'English',
    'lang.zh': 'Chinese',
    'lang.en_short': 'EN',
    'lang.zh_short': '中',
    'lang.switchToZh': 'Switch to Chinese',
    'lang.switchToEn': 'Switch to English',
    'lang.switchTitle': 'Switch Language',
    'a11y.openUserMenu': 'Open user menu',
    'a11y.signedInAs': 'Signed in as',
    'a11y.authBackgroundAlt': 'Auth Background',
    'a11y.avatarAlt': 'Avatar',
    'a11y.removePhoto': 'Remove photo',
    'home.actions.viewAll': 'View All',
    'home.actions.useTemplate': 'Use Template',
    'home.badge.premium': 'Premium',
    'home.quick.it': 'IT / Tech',
    'home.quick.finance': 'Finance',
    'home.quick.creative': 'Creative',
    'home.quick.student': 'Student',
    'home.hero.alt': 'Resume planning',
    'features.title': 'Features',
    'features.subtitle': 'Everything you need to get hired',
    'features.ai.title': 'AI Writer & Polisher',
    'features.ai.desc': 'Stuck on words? Use our Gemini-powered AI to generate summaries and improve your bullet points instantly.',
    'features.ats.title': 'ATS Friendly Templates',
    'features.ats.desc': 'Our templates are designed to pass through Applicant Tracking Systems, ensuring your resume reaches human eyes.',
    'features.share.title': 'Share Online',
    'features.share.desc': 'Publish your resume with a unique link. Track views and share directly to LinkedIn or via QR code.',
    'features.preview.title': 'Real-time Preview',
    'features.preview.desc': 'See changes instantly as you type. Drag and drop sections to reorganize your story effortlessly.',
    'templates.filters.label': 'Filters:',
    'templates.actions.useTemplate': 'Use Template',
    'templates.actions.clearAll': 'Clear all',
    'templates.actions.clearFilters': 'Clear Filters',
    'templates.badge.premium': 'Premium',
    'templates.meta.popularity': 'Popularity',
    'templates.empty': 'No templates found matching your criteria.',
    'templates.category.all': 'All',
    'templates.category.IT': 'IT',
    'templates.category.Finance': 'Finance',
    'templates.category.Creative': 'Creative',
    'templates.category.General': 'General',
    'templates.level.all': 'All',
    'templates.level.Intern': 'Intern',
    'templates.level.Junior': 'Junior',
    'templates.level.Senior': 'Senior',
    'templates.level.Executive': 'Executive',
    'editor.profile.label': 'Profile Photo',
    'editor.profile.upload': 'Upload Photo',
    'editor.profile.change': 'Change Photo',
    'editor.profile.tipSquare': 'Square image recommended (1:1).',
    'editor.profile.tipMaxSize': 'Max size 2MB (JPG/PNG).',
    'editor.fields.fullName': 'Full Name',
    'editor.fields.jobTitle': 'Job Title',
    'editor.fields.email': 'Email',
    'editor.fields.phone': 'Phone',
    'editor.fields.address': 'Address / Location',
    'editor.fields.website': 'Website / LinkedIn',
    'editor.placeholder.titleExample': 'Title (e.g. Senior Manager)',
    'editor.placeholder.subtitleExample': 'Subtitle (e.g. Company)',
    'editor.placeholder.dateRange': 'Date Range',
    'editor.placeholder.skills': 'List skills here...',
    'editor.placeholder.achievements': 'Describe your achievements...',
    'editor.ai.polishing': 'Polishing...',
    'editor.error.imageTooLarge': 'Image size too large. Please upload an image smaller than 2MB.',
    'editor.addItem': 'Add Item',
    'editor.font.group.englishSans': 'English - Sans Serif',
    'editor.font.group.englishSerif': 'English - Serif',
    'editor.font.group.englishMono': 'English - Mono',
    'editor.font.group.chineseSans': 'Chinese - Sans (黑体)',
    'editor.font.group.chineseSerif': 'Chinese - Serif (宋体/楷体)',
    'editor.font.note': 'Note: Chinese fonts rely on system availability or web fonts if supported.',
    'editor.spacing.option.compact': 'Compact (More Info)',
    'editor.spacing.option.normal': 'Normal (Balanced)',
    'editor.spacing.option.spacious': 'Spacious (Clean)',
    'editor.color.customTitle': 'Custom Color',
    'dashboard.confirm.delete': 'Are you sure you want to delete this resume?',
    'dashboard.copySuffix': ' (Copy)',
    'settings.security': 'Security',
    'settings.saveChanges': 'Save Changes',
    'settings.updatePassword': 'Update Password',
    'settings.profile.photoLabel': 'Profile Photo',
    'settings.profile.changePhoto': 'Change Photo',
    'settings.profile.photoTip': 'JPG, GIF or PNG. Max size of 800K',
    'settings.displayName': 'Display Name',
    'settings.emailAddress': 'Email Address',
    'settings.emailChangeTip': 'Contact support to change email.',
    'settings.languagePreference': 'Language Preference',
    'settings.success.profileUpdated': 'Profile updated successfully.',
    'settings.success.passwordUpdated': 'Password updated successfully.'
    ,
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmNewPassword': 'Confirm New Password'
  },
  zh: {
    'nav.templates': '模板库',
    'nav.dashboard': '我的简历',
    'nav.pricing': '订阅方案',
    'nav.signin': '登录',
    'nav.getStarted': '开始制作',
    'nav.signout': '退出登录',
    'nav.settings': '账号设置',
    'nav.profile': '个人资料',
    'hero.title': '打造您的完美简历',
    'hero.subtitle': 'AI 智能辅助',
    'hero.desc': '几分钟内构建专业、通过 ATS 筛选的简历。选择精选模板，使用 AI 润色文本，助您斩获理想 Offer。',
    'hero.cta': '创建简历',
    'hero.cta_secondary': '我的简历',
    'home.popular': '热门模板',
    'home.quickAccess': '快速入口',
    'common.edit': '编辑',
    'common.preview': '预览',
    'common.duplicate': '创建副本',
    'common.delete': '删除',
    'common.rename': '重命名',
    'common.save': '保存',
    'common.download': '下载',
    'editor.content': '内容编辑',
    'editor.design': '外观设计',
    'editor.personal': '个人信息',
    'editor.theme': '主题设置',
    'editor.font': '字体选择',
    'editor.spacing': '间距与密度',
    'editor.color': '主题颜色',
    'editor.ai_polish': 'AI 润色',
    'dashboard.title': '我的简历',
    'dashboard.createNew': '新建简历',
    'templates.title': '简历模板库',
    'templates.desc': '选择一个专业设计的模板，开始您的求职之旅。',
    'templates.filter.industry': '行业分类',
    'templates.filter.level': '职级经验',
    'templates.search': '搜索模板...',
    'footer.rights': '版权所有。',
    // Auth
    'auth.welcome': '欢迎回来',
    'auth.welcomeDesc': '输入您的账号信息以登录。',
    'auth.createAccount': '创建新账号',
    'auth.createDesc': '输入邮箱以开始注册流程。',
    'auth.email': '电子邮箱',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.verificationCode': '验证码',
    'auth.sendCode': '获取验证码',
    'auth.sending': '发送中...',
    'auth.resend': '重新发送',
    'auth.login': '登录',
    'auth.register': '注册',
    'auth.noAccount': "还没有账号？",
    'auth.hasAccount': '已有账号？',
    'auth.forgotPassword': '忘记密码？',
    'auth.terms': '点击注册即表示您同意我们的服务条款和隐私政策。',
    'auth.error.invalidEmail': '请输入有效的电子邮箱地址。',
    'auth.error.passwordMismatch': '两次输入的密码不一致。',
    'auth.error.invalidCode': '验证码错误（测试码：123456）。',
    'auth.success.codeSent': '验证码已发送至您的邮箱。',
    'auth.placeholder.email': 'you@example.com',
    'auth.placeholder.code': '123456',
    'auth.placeholder.passwordMin': '至少 6 个字符',
    'auth.placeholder.reenterPassword': '请再次输入密码',
    'auth.error.fillAll': '请填写所有字段',
    'auth.error.invalidCredentials': '邮箱或密码不正确',
    'auth.error.general': '发生错误，请稍后重试。',
    'auth.error.sendCodeFailed': '验证码发送失败。',
    'auth.error.passwordTooShort': '密码至少需要 6 个字符。',
    'auth.error.registrationFailed': '注册失败。',
    'common.backHome': '返回首页',
    'footer.product': '产品',
    'footer.legal': '法律',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.language': '语言',
    'lang.en': '英文',
    'lang.zh': '中文',
    'lang.en_short': 'EN',
    'lang.zh_short': '中',
    'lang.switchToZh': '切换为中文',
    'lang.switchToEn': '切换为英文',
    'lang.switchTitle': '切换语言',
    'a11y.openUserMenu': '打开用户菜单',
    'a11y.signedInAs': '当前登录为',
    'a11y.authBackgroundAlt': '认证背景图',
    'a11y.avatarAlt': '头像',
    'a11y.removePhoto': '移除照片',
    'home.actions.viewAll': '查看全部',
    'home.actions.useTemplate': '使用模板',
    'home.badge.premium': '高级',
    'home.quick.it': 'IT / 科技',
    'home.quick.finance': '金融',
    'home.quick.creative': '创意',
    'home.quick.student': '学生',
    'home.hero.alt': '简历规划',
    'features.title': '功能特性',
    'features.subtitle': '助你高效拿到心仪工作',
    'features.ai.title': 'AI 写作与润色',
    'features.ai.desc': '写作无从下笔？使用 Gemini 驱动的 AI 即刻生成总结并优化要点。',
    'features.ats.title': 'ATS 友好模板',
    'features.ats.desc': '模板专为通过候选人追踪系统设计，确保你的简历到达人眼。',
    'features.share.title': '在线分享',
    'features.share.desc': '发布唯一链接，追踪访问量，并可直接分享到 LinkedIn 或二维码。',
    'features.preview.title': '实时预览',
    'features.preview.desc': '输入即刻看到变化，拖拽分区轻松重组你的经历。',
    'templates.filters.label': '筛选：',
    'templates.actions.useTemplate': '使用模板',
    'templates.actions.clearAll': '清空',
    'templates.actions.clearFilters': '清除筛选',
    'templates.badge.premium': '高级',
    'templates.meta.popularity': '热度',
    'templates.empty': '没有符合条件的模板。',
    'templates.category.all': '全部',
    'templates.category.IT': 'IT',
    'templates.category.Finance': '金融',
    'templates.category.Creative': '创意',
    'templates.category.General': '通用',
    'templates.level.all': '全部',
    'templates.level.Intern': '实习',
    'templates.level.Junior': '初级',
    'templates.level.Senior': '高级',
    'templates.level.Executive': '管理层',
    'editor.profile.label': '个人照片',
    'editor.profile.upload': '上传照片',
    'editor.profile.change': '更换照片',
    'editor.profile.tipSquare': '建议使用正方形图片（1:1）。',
    'editor.profile.tipMaxSize': '最大 2MB（JPG/PNG）。',
    'editor.fields.fullName': '姓名',
    'editor.fields.jobTitle': '职位',
    'editor.fields.email': '邮箱',
    'editor.fields.phone': '电话',
    'editor.fields.address': '地址/位置',
    'editor.fields.website': '网站/领英',
    'editor.placeholder.titleExample': '标题（如：资深经理）',
    'editor.placeholder.subtitleExample': '副标题（如：公司）',
    'editor.placeholder.dateRange': '时间范围',
    'editor.placeholder.skills': '在此列出技能...',
    'editor.placeholder.achievements': '描述你的成就...',
    'editor.ai.polishing': '润色中...',
    'editor.error.imageTooLarge': '图片过大，请上传小于 2MB 的图片。',
    'editor.addItem': '添加条目',
    'editor.font.group.englishSans': '英文 - 无衬线',
    'editor.font.group.englishSerif': '英文 - 衬线',
    'editor.font.group.englishMono': '英文 - 等宽',
    'editor.font.group.chineseSans': '中文 - 黑体',
    'editor.font.group.chineseSerif': '中文 - 宋体/楷体',
    'editor.font.note': '中文字体依赖系统或支持的网页字体。',
    'editor.spacing.option.compact': '紧凑（信息更多）',
    'editor.spacing.option.normal': '正常（均衡）',
    'editor.spacing.option.spacious': '宽松（清爽）',
    'editor.color.customTitle': '自定义颜色',
    'dashboard.confirm.delete': '确定要删除这份简历吗？',
    'dashboard.copySuffix': '（副本）',
    'settings.security': '安全',
    'settings.saveChanges': '保存更改',
    'settings.updatePassword': '更新密码',
    'settings.profile.photoLabel': '个人照片',
    'settings.profile.changePhoto': '更换照片',
    'settings.profile.photoTip': 'JPG、GIF 或 PNG。最大 800K',
    'settings.displayName': '显示名称',
    'settings.emailAddress': '电子邮箱',
    'settings.emailChangeTip': '如需更改邮箱请联系支持。',
    'settings.languagePreference': '语言偏好',
    'settings.success.profileUpdated': '资料更新成功。',
    'settings.success.passwordUpdated': '密码更新成功。',
    'settings.currentPassword': '当前密码',
    'settings.newPassword': '新密码',
    'settings.confirmNewPassword': '确认新密码'
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [languageState, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('lang') as Language | null;
    return saved || 'zh';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('lang', lang);
  };

  const t = (key: string): string => {
    return translations[languageState][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language: languageState, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
