import React, { createContext, useContext, useState, ReactNode } from 'react';
import { Language } from '../types';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    'nav.templates': 'Templates',
    'nav.dashboard': 'My Resumes',
    'nav.pricing': 'Pricing',
    'nav.signin': 'Sign In',
    'nav.getStarted': 'Get Started',
    'nav.signout': 'Sign Out',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    'hero.title': 'Craft your perfect resume',
    'hero.subtitle': 'with AI precision',
    'hero.desc': 'Build professional, ATS-friendly resumes in minutes. Choose from our curated templates, use AI to polish your text, and land your dream job.',
    'hero.cta': 'Create Resume',
    'hero.cta_secondary': 'My Resumes',
    'home.popular': 'Popular Templates',
    'home.quickAccess': 'Quick Access',
    'common.edit': 'Edit',
    'common.preview': 'Preview',
    'common.duplicate': 'Duplicate',
    'common.delete': 'Delete',
    'common.rename': 'Rename',
    'common.save': 'Save',
    'common.download': 'Download',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.confirmAction': 'Confirm Action',
    'common.close': 'Close',
    'editor.content': 'Content',
    'editor.design': 'Design',
    'editor.personal': 'Personal Information',
    'editor.theme': 'Theme Settings',
    'editor.font': 'Font Family',
    'editor.spacing': 'Spacing & Density',
    'editor.color': 'Accent Color',
    'editor.ai_polish': 'AI Polish',
    'dashboard.title': 'My Resumes',
    'dashboard.createNew': 'Create New Resume',
    'templates.title': 'Resume Templates',
    'templates.desc': 'Choose a professionally designed template to get started.',
    'templates.filter.industry': 'Industry',
    'templates.filter.level': 'Level',
    'templates.search': 'Search templates...',
    'footer.rights': 'All rights reserved.',
    // Auth
    'auth.welcome': 'Welcome back',
    'auth.welcomeDesc': 'Enter your details to access your account.',
    'auth.orContinueWith': 'Or continue with',
    'auth.provider.github': 'GitHub',
    'auth.provider.wechat': 'WeChat',
    'auth.createAccount': 'Create an account',
    'auth.createDesc': 'Enter your email to get started.',
    'auth.email': 'Email Address',
    'auth.password': 'Password',
    'auth.confirmPassword': 'Confirm Password',
    'auth.verificationCode': 'Verification Code',
    'auth.sendCode': 'Send Code',
    'auth.sending': 'Sending...',
    'auth.resend': 'Resend in',
    'auth.login': 'Sign In',
    'auth.register': 'Sign Up',
    'auth.noAccount': "Don't have an account?",
    'auth.hasAccount': 'Already have an account?',
    'auth.forgotPassword': 'Forgot password?',
    'auth.terms': 'By clicking continue, you agree to our Terms of Service and Privacy Policy.',
    'auth.error.invalidEmail': 'Please enter a valid email.',
    'auth.error.passwordMismatch': 'Passwords do not match.',
    'auth.error.invalidCode': 'Invalid verification code.',
    'auth.success.codeSent': 'Verification code sent to your email.',
    'auth.quote': 'Success is not final, failure is not fatal: it is the courage to continue that counts.',
    'auth.quoteAuthor': 'Winston Churchill',
    'auth.placeholder.email': 'you@example.com',
    'auth.placeholder.code': '123456',
    'auth.placeholder.password': '••••••••',
    'auth.placeholder.passwordMin': 'Min 6 characters',
    'auth.placeholder.reenterPassword': 'Re-enter password',
    'auth.error.fillAll': 'Please fill in all fields',
    'auth.error.invalidCredentials': 'Invalid email or password',
    'auth.error.general': 'An error occurred. Please try again.',
    'auth.error.sendCodeFailed': 'Failed to send code.',
    'auth.error.passwordTooShort': 'Password must be at least 6 characters.',
    'auth.error.registrationFailed': 'Registration failed.',
    'common.backHome': 'Back to Home',
    'footer.product': 'Product',
    'footer.legal': 'Legal',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.language': 'Language',
    'lang.en': 'English',
    'lang.zh': 'Chinese',
    'lang.en_short': 'EN',
    'lang.zh_short': '中',
    'lang.switchToZh': 'Switch to Chinese',
    'lang.switchToEn': 'Switch to English',
    'lang.switchTitle': 'Switch Language',
    'a11y.openUserMenu': 'Open user menu',
    'a11y.signedInAs': 'Signed in as',
    'a11y.authBackgroundAlt': 'Auth Background',
    'a11y.avatarAlt': 'Avatar',
    'a11y.drag': 'Drag',
    'a11y.removePhoto': 'Remove photo',
    'home.actions.viewAll': 'View All',
    'home.actions.useTemplate': 'Use Template',
    'home.badge.premium': 'Premium',
    'home.quick.it': 'IT / Tech',
    'home.quick.finance': 'Finance',
    'home.quick.creative': 'Creative',
    'home.quick.student': 'Student',
    'home.hero.alt': 'Resume planning',
    'features.title': 'Features',
    'features.subtitle': 'Everything you need to get hired',
    'features.ai.title': 'AI Writer & Polisher',
    'features.ai.desc': 'Stuck on words? Use our Gemini-powered AI to generate summaries and improve your bullet points instantly.',
    'features.ats.title': 'ATS Friendly Templates',
    'features.ats.desc': 'Our templates are designed to pass through Applicant Tracking Systems, ensuring your resume reaches human eyes.',
    'features.share.title': 'Share Online',
    'features.share.desc': 'Publish your resume with a unique link. Track views and share directly to LinkedIn or via QR code.',
    'features.preview.title': 'Real-time Preview',
    'features.preview.desc': 'See changes instantly as you type. Drag and drop sections to reorganize your story effortlessly.',
    'preview.pagesHint': 'Estimated pages: {count} pages',
    'rte.tooltip.bold': 'Bold',
    'rte.tooltip.italic': 'Italic',
    'rte.tooltip.bullets': 'Bulleted list',
    'rte.tooltip.undo': 'Undo',
    'rte.tooltip.redo': 'Redo',
    'templates.filters.label': 'Filters:',
    'templates.actions.useTemplate': 'Use Template',
    'templates.actions.clearAll': 'Clear all',
    'templates.actions.clearFilters': 'Clear Filters',
    'templates.badge.premium': 'Premium',
    'templates.meta.popularity': 'Popularity',
    'templates.empty': 'No templates found matching your criteria.',
    'templates.category.all': 'All',
    'templates.category.IT': 'IT',
    'templates.category.Finance': 'Finance',
    'templates.category.Creative': 'Creative',
    'templates.category.General': 'General',
    'templates.level.all': 'All',
    'templates.level.Intern': 'Intern',
    'templates.level.Junior': 'Junior',
    'templates.level.Senior': 'Senior',
    'templates.level.Executive': 'Executive',
    'editor.profile.label': 'Profile Photo',
    'editor.profile.upload': 'Upload Photo',
    'editor.profile.change': 'Change Photo',
    'editor.profile.tipSquare': 'Square image recommended (1:1).',
    'editor.profile.tipMaxSize': 'Max size 2MB (JPG/PNG).',
    'editor.fields.fullName': 'Full Name',
    'editor.fields.jobTitle': 'Job Title',
    'editor.fields.email': 'Email',
    'editor.fields.phone': 'Phone',
    'editor.fields.website': 'Website / LinkedIn',
    'editor.fields.gender': 'Gender',
    'editor.fields.age': 'Age',
    'editor.fields.maritalStatus': 'Marital Status',
    'editor.fields.politicalStatus': 'Political Status',
    'editor.fields.birthplace': 'Birthplace',
    'editor.fields.ethnicity': 'Ethnicity',
    'editor.fields.height': 'Height',
    'editor.fields.weight': 'Weight',
    'editor.customInfo.title': 'Custom Information',
    'editor.customInfo.add': 'Add Custom Item',
    'editor.customInfo.label': 'Label',
    'editor.customInfo.value': 'Value',
    'editor.placeholder.titleExample': 'Title (e.g. Senior Manager)',
    'editor.placeholder.subtitleExample': 'Subtitle (e.g. Company)',
    'editor.placeholder.dateRange': 'Date Range',
    'editor.placeholder.skills': 'List skills here...',
    'editor.placeholder.achievements': 'Describe your achievements...',
    'editor.ai.polishing': 'Polishing...',
    'editor.error.imageTooLarge': 'Image size too large. Please upload an image smaller than 2MB.',
    'editor.addItem': 'Add Item',
    'editor.font.group.englishSans': 'English - Sans Serif',
    'editor.font.group.englishSerif': 'English - Serif',
    'editor.font.group.englishMono': 'English - Mono',
    'editor.font.group.chineseSans': 'Chinese - Sans (黑体)',
    'editor.font.group.chineseSerif': 'Chinese - Serif (宋体/楷体)',
    'editor.font.note': 'Note: Chinese fonts rely on system availability or web fonts if supported.',
    'editor.spacing.option.compact': 'Compact (More Info)',
    'editor.spacing.option.normal': 'Normal (Balanced)',
    'editor.spacing.option.spacious': 'Spacious (Clean)',
    'editor.color.customTitle': 'Custom Color',
    'editor.back': 'Back',
    'editor.addSection': 'Add Custom Section',
    'editor.removeSection': 'Remove Section',
    'editor.rename': 'Rename Section',
    'editor.toggleVisibility': 'Toggle Visibility',
    'editor.template': 'Template',
    'editor.save': 'Save',
    'editor.export.pdf': 'PDF',
    'editor.export.png': 'PNG',
    'editor.export.failed': 'Export failed',
    'editor.success.saved': 'Resume saved successfully',
    'font.inter': 'Inter (Modern)',
    'font.roboto': 'Roboto (Technical)',
    'font.merriweather': 'Merriweather (Elegant)',
    'font.playfair': 'Playfair Display (Classy)',
    'font.mono': 'Roboto Mono (Code)',
    'font.yahei': '微软雅黑 (Microsoft YaHei)',
    'font.notosans': '思源黑体 (Noto Sans SC)',
    'font.simsun': '宋体 (SimSun)',
    'font.kaiti': '楷体 (KaiTi)',
    'dashboard.confirm.delete': 'Are you sure you want to delete this resume?',
    'dashboard.copySuffix': ' (Copy)',
    'settings.security': 'Security',
    'settings.saveChanges': 'Save Changes',
    'settings.updatePassword': 'Update Password',
    'settings.profile.photoLabel': 'Profile Photo',
    'settings.profile.changePhoto': 'Change Photo',
    'settings.profile.photoTip': 'JPG, GIF or PNG. Max size of 800K',
    'settings.displayName': 'Display Name',
    'settings.emailAddress': 'Email Address',
    'settings.emailChangeTip': 'Contact support to change email.',
    'settings.languagePreference': 'Language Preference',
    'settings.success.profileUpdated': 'Profile updated successfully.',
    'settings.success.passwordUpdated': 'Password updated successfully.'
    ,
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmNewPassword': 'Confirm New Password',
    'section.summary': 'Professional Summary',
    'section.experience': 'Work Experience',
    'section.education': 'Education',
    'section.skills': 'Skills',
    'section.projects': 'Projects',
    'section.custom': 'Custom Section',
    // Pricing
    'pricing.title': 'Pricing Plans',
    'pricing.subtitle': 'Simple, transparent pricing for everyone.',
    'pricing.basic': 'Basic',
    'pricing.pro': 'Pro',
    'pricing.basicDesc': 'Best for individuals.',
    'pricing.proDesc': 'Best for power users.',
    'pricing.price.free': '$0',
    'pricing.price.pro': '$0',
    'pricing.month': '/mo',
    'pricing.buy': 'Buy',
    'pricing.modal.title': 'Notice',
    'pricing.modal.planning': 'Planning in progress...',
    'pricing.modal.close': 'Close'
    ,
    'nav.admin': 'Admin',
    'admin.title': 'Admin',
    'admin.backDashboard': 'Back to Dashboard',
    'admin.users': 'Users',
    'admin.resumes': 'Resumes',
    'admin.templates': 'Templates',
    'admin.shares': 'Shares',
    'admin.search': 'Search',
    'admin.keyword': 'Keyword',
    'admin.slugKeyword': 'Slug keyword',
    'admin.titleKeyword': 'Title keyword',
    'admin.columns.id': 'ID',
    'admin.columns.email': 'Email',
    'admin.columns.name': 'Name',
    'admin.columns.role': 'Role',
    'admin.columns.status': 'Status',
    'admin.columns.actions': 'Actions',
    'admin.columns.user': 'User',
    'admin.columns.title': 'Title',
    'admin.columns.template': 'Template',
    'admin.columns.slug': 'Slug',
    'admin.status.active': 'Active',
    'admin.status.inactive': 'Inactive',
    'admin.prev': 'Previous',
    'admin.next': 'Next',
    'admin.total': 'Total',
    'admin.pageSize': 'Page Size',
    'admin.actions.ban': 'Ban',
    'admin.actions.unban': 'Unban',
    'admin.actions.resetPassword': 'Reset Password',
    'admin.actions.delete': 'Delete',
    'admin.actions.transferOwner': 'Transfer Owner',
    'admin.actions.setPublic': 'Set Public',
    'admin.actions.setPrivate': 'Set Private',
    'admin.actions.create': 'Create',
    'admin.actions.update': 'Update',
    'admin.actions.preview': 'Preview',
    'admin.value.yes': 'Yes',
    'admin.value.no': 'No',
    'admin.msg.loadUsersFailed': 'Failed to load users.',
    'admin.msg.roleUpdated': 'Role updated.',
    'admin.msg.roleUpdateFailed': 'Failed to update role.',
    'admin.msg.banned': 'User banned.',
    'admin.msg.banFailed': 'Failed to ban user.',
    'admin.msg.unbanned': 'User unbanned.',
    'admin.msg.unbanFailed': 'Failed to unban user.',
    'admin.msg.newPassword': 'New password:',
    'admin.msg.resetFailed': 'Reset failed.',
    'admin.msg.loadResumesFailed': 'Failed to load resumes.',
    'admin.msg.deleted': 'Deleted.',
    'admin.msg.deleteFailed': 'Delete failed.',
    'admin.msg.transferred': 'Transferred.',
    'admin.msg.transferFailed': 'Transfer failed.',
    'admin.msg.setPublicSuccess': 'Set to public.',
    'admin.msg.setPublicFailed': 'Failed to set visibility.',
    'admin.msg.loadSharesFailed': 'Failed to load shares.',
    'admin.msg.visibilityUpdated': 'Visibility updated.',
    'admin.msg.visibilityUpdateFailed': 'Failed to update visibility.',
    'admin.msg.templateCreated': 'Template created.',
    'admin.msg.templateCreateFailed': 'Failed to create template.',
    'admin.msg.templateUpdated': 'Template updated.',
    'admin.msg.templateUpdateFailed': 'Failed to update template.',
    'admin.msg.templateDeleted': 'Template deleted.',
    'admin.msg.templateDeleteFailed': 'Failed to delete template.',
    'admin.confirm.ban': 'Ban this user?',
    'admin.confirm.resetPassword': 'Reset password for this user?',
    'admin.confirm.deleteResume': 'Delete this resume?',
    'admin.confirm.setPublic': 'Set this resume to public?',
    'admin.confirm.deleteShare': 'Delete this share link?',
    'admin.input.newOwnerId': 'Enter new owner user ID',
    'admin.form.externalId': 'External ID',
    'admin.form.name': 'Name',
    'admin.form.thumbnail': 'Thumbnail URL',
    'admin.form.tags': 'Tags (comma separated)',
    'admin.form.category': 'Category',
    'admin.form.level': 'Level',
    'admin.form.popularity': 'Popularity',
    'admin.form.isPremium': 'Premium'
  },
  zh: {
    'nav.templates': '模板库',
    'nav.dashboard': '我的简历',
    'nav.pricing': '订阅方案',
    'nav.signin': '登录',
    'nav.getStarted': '开始制作',
    'nav.signout': '退出登录',
    'nav.settings': '账号设置',
    'nav.profile': '个人资料',
    'hero.title': '打造您的完美简历',
    'hero.subtitle': 'AI 智能辅助',
    'hero.desc': '几分钟内构建专业、通过 ATS 筛选的简历。选择精选模板，使用 AI 润色文本，助您斩获理想 Offer。',
    'hero.cta': '创建简历',
    'hero.cta_secondary': '我的简历',
    'home.popular': '热门模板',
    'home.quickAccess': '快速入口',
    'common.edit': '编辑',
    'common.preview': '预览',
    'common.duplicate': '创建副本',
    'common.delete': '删除',
    'common.rename': '重命名',
    'common.save': '保存',
    'common.download': '下载',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.confirmAction': '确认操作',
    'common.close': '关闭',
    'editor.content': '内容编辑',
    'editor.design': '外观设计',
    'editor.personal': '个人信息',
    'editor.theme': '主题设置',
    'editor.font': '字体选择',
    'editor.spacing': '间距与密度',
    'editor.color': '主题颜色',
    'editor.ai_polish': 'AI 润色',
    'dashboard.title': '我的简历',
    'dashboard.createNew': '新建简历',
    'templates.title': '简历模板库',
    'templates.desc': '选择一个专业设计的模板，开始您的求职之旅。',
    'templates.filter.industry': '行业分类',
    'templates.filter.level': '职级经验',
    'templates.search': '搜索模板...',
    'footer.rights': '版权所有。',
    // Auth
    'auth.welcome': '欢迎回来',
    'auth.welcomeDesc': '输入您的账号信息以登录。',
    'auth.orContinueWith': '或使用以下方式继续',
    'auth.provider.github': 'GitHub',
    'auth.provider.wechat': '微信',
    'auth.createAccount': '创建新账号',
    'auth.createDesc': '输入邮箱以开始注册流程。',
    'auth.email': '电子邮箱',
    'auth.password': '密码',
    'auth.confirmPassword': '确认密码',
    'auth.verificationCode': '验证码',
    'auth.sendCode': '获取验证码',
    'auth.sending': '发送中...',
    'auth.resend': '重新发送',
    'auth.login': '登录',
    'auth.register': '注册',
    'auth.noAccount': "还没有账号？",
    'auth.hasAccount': '已有账号？',
    'auth.forgotPassword': '忘记密码？',
    'auth.terms': '点击注册即表示您同意我们的服务条款和隐私政策。',
    'auth.error.invalidEmail': '请输入有效的电子邮箱地址。',
    'auth.error.passwordMismatch': '两次输入的密码不一致。',
    'auth.error.invalidCode': '验证码错误（测试码：123456）。',
    'auth.success.codeSent': '验证码已发送至您的邮箱。',
    'auth.quote': '成功不是终点，失败也非末日：关键在于继续前行的勇气。',
    'auth.quoteAuthor': '温斯顿·丘吉尔',
    'auth.placeholder.email': 'you@example.com',
    'auth.placeholder.code': '123456',
    'auth.placeholder.password': '••••••••',
    'auth.placeholder.passwordMin': '至少 6 个字符',
    'auth.placeholder.reenterPassword': '请再次输入密码',
    'auth.error.fillAll': '请填写所有字段',
    'auth.error.invalidCredentials': '邮箱或密码不正确',
    'auth.error.general': '发生错误，请稍后重试。',
    'auth.error.sendCodeFailed': '验证码发送失败。',
    'auth.error.passwordTooShort': '密码至少需要 6 个字符。',
    'auth.error.registrationFailed': '注册失败。',
    'common.backHome': '返回首页',
    'footer.product': '产品',
    'footer.legal': '法律',
    'footer.privacy': '隐私政策',
    'footer.terms': '服务条款',
    'footer.language': '语言',
    'lang.en': '英文',
    'lang.zh': '中文',
    'lang.en_short': 'EN',
    'lang.zh_short': '中',
    'lang.switchToZh': '切换为中文',
    'lang.switchToEn': '切换为英文',
    'lang.switchTitle': '切换语言',
    'a11y.openUserMenu': '打开用户菜单',
    'a11y.signedInAs': '当前登录为',
    'a11y.authBackgroundAlt': '认证背景图',
    'a11y.avatarAlt': '头像',
    'a11y.drag': '拖拽',
    'a11y.removePhoto': '移除照片',
    'home.actions.viewAll': '查看全部',
    'home.actions.useTemplate': '使用模板',
    'home.badge.premium': '高级',
    'home.quick.it': 'IT / 科技',
    'home.quick.finance': '金融',
    'home.quick.creative': '创意',
    'home.quick.student': '学生',
    'home.hero.alt': '简历规划',
    'features.title': '功能特性',
    'features.subtitle': '助你高效拿到心仪工作',
    'features.ai.title': 'AI 写作与润色',
    'features.ai.desc': '写作无从下笔？使用 Gemini 驱动的 AI 即刻生成总结并优化要点。',
    'features.ats.title': 'ATS 友好模板',
    'features.ats.desc': '模板专为通过候选人追踪系统设计，确保你的简历到达人眼。',
    'features.share.title': '在线分享',
    'features.share.desc': '发布唯一链接，追踪访问量，并可直接分享到 LinkedIn 或二维码。',
    'features.preview.title': '实时预览',
    'features.preview.desc': '输入即刻看到变化，拖拽分区轻松重组你的经历。',
    'preview.pagesHint': '预计分页：共 {count} 页',
    'rte.tooltip.bold': '加粗',
    'rte.tooltip.italic': '斜体',
    'rte.tooltip.bullets': '项目符号',
    'rte.tooltip.undo': '撤销',
    'rte.tooltip.redo': '重做',
    'templates.filters.label': '筛选：',
    'templates.actions.useTemplate': '使用模板',
    'templates.actions.clearAll': '清空',
    'templates.actions.clearFilters': '清除筛选',
    'templates.badge.premium': '高级',
    'templates.meta.popularity': '热度',
    'templates.empty': '没有符合条件的模板。',
    'templates.category.all': '全部',
    'templates.category.IT': 'IT',
    'templates.category.Finance': '金融',
    'templates.category.Creative': '创意',
    'templates.category.General': '通用',
    'templates.level.all': '全部',
    'templates.level.Intern': '实习',
    'templates.level.Junior': '初级',
    'templates.level.Senior': '高级',
    'templates.level.Executive': '管理层',
    'editor.profile.label': '个人照片',
    'editor.profile.upload': '上传照片',
    'editor.profile.change': '更换照片',
    'editor.profile.tipSquare': '建议使用正方形图片（1:1）。',
    'editor.profile.tipMaxSize': '最大 2MB（JPG/PNG）。',
    'editor.fields.fullName': '姓名',
    'editor.fields.jobTitle': '职位',
    'editor.fields.email': '邮箱',
    'editor.fields.phone': '电话',
    'editor.fields.website': '网站/领英',
    'editor.fields.gender': '性别',
    'editor.fields.age': '年龄',
    'editor.fields.maritalStatus': '婚姻状况',
    'editor.fields.politicalStatus': '政治面貌',
    'editor.fields.birthplace': '籍贯',
    'editor.fields.ethnicity': '民族',
    'editor.fields.height': '身高',
    'editor.fields.weight': '体重',
    'editor.customInfo.title': '自定义信息',
    'editor.customInfo.add': '添加自定义信息',
    'editor.customInfo.label': '名称',
    'editor.customInfo.value': '内容',
    'editor.placeholder.titleExample': '标题（如：资深经理）',
    'editor.placeholder.subtitleExample': '副标题（如：公司）',
    'editor.placeholder.dateRange': '时间范围',
    'editor.placeholder.skills': '在此列出技能...',
    'editor.placeholder.achievements': '描述你的成就...',
    'editor.ai.polishing': '润色中...',
    'editor.error.imageTooLarge': '图片过大，请上传小于 2MB 的图片。',
    'editor.addItem': '添加条目',
    'editor.font.group.englishSans': '英文 - 无衬线',
    'editor.font.group.englishSerif': '英文 - 衬线',
    'editor.font.group.englishMono': '英文 - 等宽',
    'editor.font.group.chineseSans': '中文 - 黑体',
    'editor.font.group.chineseSerif': '中文 - 宋体/楷体',
    'editor.font.note': '中文字体依赖系统或支持的网页字体。',
    'editor.spacing.option.compact': '紧凑（信息更多）',
    'editor.spacing.option.normal': '正常（均衡）',
    'editor.spacing.option.spacious': '宽松（清爽）',
    'editor.color.customTitle': '自定义颜色',
    'editor.back': '返回',
    'editor.addSection': '添加自定义模块',
    'editor.removeSection': '删除模块',
    'editor.rename': '重命名模块',
    'editor.toggleVisibility': '切换显示',
    'editor.template': '切换模板',
    'editor.save': '保存',
    'editor.export.pdf': '导出 PDF',
    'editor.export.png': '导出图片',
    'editor.export.failed': '导出失败',
    'editor.success.saved': '简历保存成功',
    'font.inter': 'Inter (现代)',
    'font.roboto': 'Roboto (技术)',
    'font.merriweather': 'Merriweather (优雅)',
    'font.playfair': 'Playfair Display (经典)',
    'font.mono': 'Roboto Mono (代码)',
    'font.yahei': '微软雅黑 (Microsoft YaHei)',
    'font.notosans': '思源黑体 (Noto Sans SC)',
    'font.simsun': '宋体 (SimSun)',
    'font.kaiti': '楷体 (KaiTi)',
    'dashboard.confirm.delete': '确定要删除这份简历吗？',
    'dashboard.copySuffix': '（副本）',
    'settings.security': '安全',
    'settings.saveChanges': '保存更改',
    'settings.updatePassword': '更新密码',
    'settings.profile.photoLabel': '个人照片',
    'settings.profile.changePhoto': '更换照片',
    'settings.profile.photoTip': 'JPG、GIF 或 PNG。最大 800K',
    'settings.displayName': '显示名称',
    'settings.emailAddress': '电子邮箱',
    'settings.emailChangeTip': '如需更改邮箱请联系支持。',
    'settings.languagePreference': '语言偏好',
    'settings.success.profileUpdated': '资料更新成功。',
    'settings.success.passwordUpdated': '密码更新成功。',
    'settings.currentPassword': '当前密码',
    'settings.newPassword': '新密码',
    'settings.confirmNewPassword': '确认新密码',
    'section.summary': '个人总结',
    'section.experience': '工作经历',
    'section.education': '教育背景',
    'section.skills': '技能特长',
    'section.projects': '项目经历',
    'section.custom': '自定义模块',
    // Pricing
    'pricing.title': '订阅方案',
    'pricing.subtitle': '简单透明的定价方案。',
    'pricing.basic': '基础版',
    'pricing.pro': '专业版',
    'pricing.basicDesc': '适合个人使用。',
    'pricing.proDesc': '适合资深用户。',
    'pricing.price.free': '¥0',
    'pricing.price.pro': '¥0',
    'pricing.month': '/月',
    'pricing.buy': '购买',
    'pricing.modal.title': '提示',
    'pricing.modal.planning': '正在规划中...',
    'pricing.modal.close': '关闭'
    ,
    'nav.admin': '管理后台',
    'admin.title': '管理后台',
    'admin.backDashboard': '返回仪表盘',
    'admin.users': '用户',
    'admin.resumes': '简历',
    'admin.templates': '模板',
    'admin.shares': '分享',
    'admin.search': '搜索',
    'admin.keyword': '关键字',
    'admin.slugKeyword': 'Slug 关键字',
    'admin.titleKeyword': '标题关键字',
    'admin.columns.id': 'ID',
    'admin.columns.email': '邮箱',
    'admin.columns.name': '姓名',
    'admin.columns.role': '角色',
    'admin.columns.status': '状态',
    'admin.columns.actions': '操作',
    'admin.columns.user': '用户',
    'admin.columns.title': '标题',
    'admin.columns.template': '模板',
    'admin.columns.slug': 'Slug',
    'admin.status.active': '启用',
    'admin.status.inactive': '禁用',
    'admin.prev': '上一页',
    'admin.next': '下一页',
    'admin.total': '共',
    'admin.pageSize': '每页',
    'admin.actions.ban': '封禁',
    'admin.actions.unban': '解禁',
    'admin.actions.resetPassword': '重置密码',
    'admin.actions.delete': '删除',
    'admin.actions.transferOwner': '转移所有者',
    'admin.actions.setPublic': '设为公开',
    'admin.actions.setPrivate': '设为私密',
    'admin.actions.create': '创建',
    'admin.actions.update': '更新',
    'admin.actions.preview': '预览',
    'admin.value.yes': '是',
    'admin.value.no': '否',
    'admin.msg.loadUsersFailed': '无法获取用户列表。',
    'admin.msg.roleUpdated': '角色已更新。',
    'admin.msg.roleUpdateFailed': '更新角色失败。',
    'admin.msg.banned': '已封禁。',
    'admin.msg.banFailed': '封禁失败。',
    'admin.msg.unbanned': '已解禁。',
    'admin.msg.unbanFailed': '解禁失败。',
    'admin.msg.newPassword': '新密码：',
    'admin.msg.resetFailed': '重置失败。',
    'admin.msg.loadResumesFailed': '无法获取简历列表。',
    'admin.msg.deleted': '已删除。',
    'admin.msg.deleteFailed': '删除失败。',
    'admin.msg.transferred': '已转移。',
    'admin.msg.transferFailed': '转移失败。',
    'admin.msg.setPublicSuccess': '已公开。',
    'admin.msg.setPublicFailed': '设置失败。',
    'admin.msg.loadSharesFailed': '无法获取分享列表。',
    'admin.msg.visibilityUpdated': '已更新公开性。',
    'admin.msg.visibilityUpdateFailed': '更新失败。',
    'admin.msg.templateCreated': '模板已创建。',
    'admin.msg.templateCreateFailed': '创建失败。',
    'admin.msg.templateUpdated': '模板已更新。',
    'admin.msg.templateUpdateFailed': '更新失败。',
    'admin.msg.templateDeleted': '模板已删除。',
    'admin.msg.templateDeleteFailed': '删除失败。',
    'admin.confirm.ban': '确认封禁该用户？',
    'admin.confirm.resetPassword': '为该用户重置密码？',
    'admin.confirm.deleteResume': '确认删除该简历？',
    'admin.confirm.setPublic': '将该简历设为公开？',
    'admin.confirm.deleteShare': '确认删除该分享链接？',
    'admin.input.newOwnerId': '请输入新的所有者用户 ID',
    'admin.form.externalId': 'External ID',
    'admin.form.name': '名称',
    'admin.form.thumbnail': '缩略图 URL',
    'admin.form.tags': '标签（逗号分隔）',
    'admin.form.category': '分类',
    'admin.form.level': '等级',
    'admin.form.popularity': '热度',
    'admin.form.isPremium': '付费模板'
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [languageState, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('lang') as Language | null;
    return saved || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('lang', lang);
  };

  const t = (key: string): string => {
    return translations[languageState][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language: languageState, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
